In [12]:
import yfinance as yf
import pandas as pd
import os

# Data Loading and Pre-Processing

## Seleksi daftar IDX dan pengelompokkan saham

### Akses isi file DaftarSaham

In [3]:
df = pd.read_excel("DaftarSaham.xlsx")

df.head()

,No,Kode,Nama Perusahaan,Tanggal Pencatatan,Saham,Papan Pencatatan
0,1,AALI,Astra Agro Lestari Tbk.,09 Des 1997,1.924.688.333,Utama
1,2,ABBA,Mahaka Media Tbk.,03 Apr 2002,3.935.892.857,Pemantauan Khusus
2,3,ABDA,Asuransi Bina Dana Arta Tbk.,06 Jul 1989,620.806.680,Pemantauan Khusus
3,4,ABMM,ABM Investama Tbk.,06 Des 2011,2.753.165.000,Utama
4,5,ACES,Aspirasi Hidup Indonesia Tbk.,06 Nov 2007,17.120.389.700,Utama

In [4]:
len(df)

956

### Filter saham, pilih yang sudah aktif dari tahun <= 2020

In [6]:
# Mapping bulan Indonesia ke Inggris
bulan_map = {
    "Jan": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Apr": "Apr",
    "Mei": "May",
    "Jun": "Jun",
    "Jul": "Jul",
    "Agt": "Aug",
    "Sep": "Sep",
    "Okt": "Oct",
    "Nov": "Nov",
    "Des": "Dec"
}

for indo, eng in bulan_map.items():
    df["Tanggal Pencatatan"] = df["Tanggal Pencatatan"].str.replace(indo, eng, regex=False)

df["Tanggal Pencatatan"] = pd.to_datetime(df["Tanggal Pencatatan"], dayfirst=True)

df.head()

,No,Kode,Nama Perusahaan,Tanggal Pencatatan,Saham,Papan Pencatatan
0,1,AALI,Astra Agro Lestari Tbk.,1997-12-09,1.924.688.333,Utama
1,2,ABBA,Mahaka Media Tbk.,2002-04-03,3.935.892.857,Pemantauan Khusus
2,3,ABDA,Asuransi Bina Dana Arta Tbk.,1989-07-06,620.806.680,Pemantauan Khusus
3,4,ABMM,ABM Investama Tbk.,2011-12-06,2.753.165.000,Utama
4,5,ACES,Aspirasi Hidup Indonesia Tbk.,2007-11-06,17.120.389.700,Utama

In [7]:
df_pre2020 = df[df["Tanggal Pencatatan"] <= "2020-01-01"]

len(df_pre2020)

646

In [10]:
list_pre2020 = []
for i in df_pre2020["Kode"]:
    list_pre2020.append(i)

In [39]:
print(len(list_pre2020))

646

### Pengelompokkan berdasarkan Sektor

In [16]:
list_sektor = []

path_sektor = "daftar_sektor/"

files = os.listdir(path_sektor)

for filename in files:
    list_sektor.append(filename[:-5])

In [17]:
list_sektor

['barang_baku',
 'barang_konsumsi_non_primer',
 'barang_konsumsi_primer',
 'energi',
 'industrial',
 'infrastruktur',
 'kesehatan',
 'keuangan',
 'properti',
 'teknologi',
 'transportasi_dan_logistik']

In [23]:
daftar_sektor = {}

for sektor in list_sektor:
    ls_saham_sektor = []
    df = pd.read_excel(f"daftar_sektor/{sektor}.xlsx")
    dft_saham = df["Kode"]
    for saham in dft_saham:
        ls_saham_sektor.append(saham)
    daftar_sektor[sektor] = ls_saham_sektor

In [ ]:
n = 0
for saham in daftar_sektor:
    print(f'{saham}: {len(daftar_sektor[saham])}')
    n += len(daftar_sektor[saham])
print(n)

barang_baku: 113
barang_konsumsi_non_primer: 163
barang_konsumsi_primer: 132
energi: 91
industrial: 65
infrastruktur: 70
kesehatan: 38
keuangan: 106
properti: 92
teknologi: 47
transportasi_dan_logistik: 40
957

In [48]:
terkelompok = {}

for sektor in daftar_sektor:
    list_kelompok = []
    for saham in daftar_sektor[sektor]:
        if saham in list_pre2020:
            list_kelompok.append(saham)
    terkelompok[sektor] = list_kelompok

In [49]:
n = 0
for saham in terkelompok:
    print(f'{saham}: {len(terkelompok[saham])}')
    n += len(terkelompok[saham])
print(n)

barang_baku: 81
barang_konsumsi_non_primer: 107
barang_konsumsi_primer: 77
energi: 64
industrial: 46
infrastruktur: 49
kesehatan: 18
keuangan: 96
properti: 65
teknologi: 18
transportasi_dan_logistik: 25
646

In [50]:
terkelompok

{'barang_baku': ['AKPI',
  'ALDO',
  'ALKA',
  'ALMI',
  'ANTM',
  'APLI',
  'BAJA',
  'BMSR',
  'BRMS',
  'BRNA',
  'BRPT',
  'BTON',
  'CITA',
  'CLPI',
  'CTBN',
  'DKFT',
  'DPNS',
  'EKAD',
  'ESSA',
  'ETWA',
  'FASW',
  'FPNI',
  'GDST',
  'IGAR',
  'INAI',
  'INCI',
  'INCO',
  'INKP',
  'INRU',
  'INTD',
  'INTP',
  'IPOL',
  'ISSP',
  'KBRI',
  'KDSI',
  'KRAS',
  'LMSH',
  'LTLS',
  'MDKA',
  'NIKL',
  'OKAS',
  'PICO',
  'PSAB',
  'SIMA',
  'SMBR',
  'SMCB',
  'SMGR',
  'SPMA',
  'SQMI',
  'SRSN',
  'SULI',
  'TALF',
  'TBMS',
  'TINS',
  'TIRT',
  'TKIM',
  'TPIA',
  'TRST',
  'UNIC',
  'WTON',
  'YPAS',
  'INCF',
  'WSBP',
  'KMTR',
  'MDKI',
  'ZINC',
  'PBID',
  'TDPM',
  'SWAT',
  'MOLI',
  'HKMU',
  'KAYU',
  'SMKL',
  'GGRP',
  'OPMS',
  'PURE',
  'ESIP',
  'IFSH',
  'IFII',
  'ADMG',
  'AGII'],
 'barang_konsumsi_non_primer': ['ABBA',
  'ACES',
  'AKKU',
  'ARGO',
  'ARTA',
  'AUTO',
  'BATA',
  'BAYU',
  'BIMA',
  'BLTZ',
  'BMTR',
  'BOLT',
  'BRAM',
  'BUVA',
  'CINT',
  'CNTX',
  'CSAP',
  'ECII',
  'ERAA',
  'ERTX',
  'ESTI',
  'FAST',
  'FORU',
  'GDYR',
  'GEMA',
  'GJTL',
  'GLOB',
  'GWSA',
  'HOME',
  'HOTL',
  'IIKP',
  'IMAS',
  'INDR',
  'INDS',
  'JIHD',
  'JSPT',
  'KICI',
  'KPIG',
  'LMPI',
  'LPIN',
  'LPPF',
  'MAPI',
  'MDIA',
  'MGNA',
  'MICE',
  'MNCN',
  'MPMX',
  'MSKY',
  'MYTX',
  'PANR',
  'PBRX',
  'PDES',
  'PGLI',
  'PJAA',
  'PSKT',
  'PTSP',
  'RALS',
  'RICY',
  'SCMA',
  'SHID',
  'SMSM',
  'SONA',
  'SRIL',
  'SSTM',
  'TELE',
  'TFCO',
  'TMPO',
  'TRIO',
  'TRIS',
  'UNIT',
  'VIVA',
  'JGLE',
  'MARI',
  'MKNT',
  'BOGA',
  'CARS',
  'MINA',
  'MAPB',
  'WOOD',
  'HRTA',
  'MABA',
  'BELL',
  'DFAM',
  'PZZA',
  'MSIN',
  'MAPA',
  'NUSA',
  'FILM',
  'DIGI',
  'DUCK',
  'YELO',
  'SOTS',
  'ZONE',
  'CLAY',
  'NATO',
  'HRME',
  'FITT',
  'BOLA',
  'POLU',
  'IPTV',
  'EAST',
  'KOTA',
  'INOV',
  'SLIS',
  'PMJS',
  'PNSE',
  'POLY'],
 'barang_konsumsi_primer': ['AALI',
  'ADES',
  'AISA',
  'ALTO',
  'AMRT',
  'ANJT',
  'BISI',
  'BTEK',
  'BUDI',
  'BWPT',
  'CEKA',
  'CPIN',
  'CPRO',
  'DLTA',
  'DSFI',
  'DSNG',
  'EPMT',
  'FISH',
  'GGRM',
  'GOLL',
  'GZCO',
  'HERO',
  'HMSP',
  'ICBP',
  'INDF',
  'JAWA',
  'JPFA',
  'LAPD',
  'LSIP',
  'MAGP',
  'MAIN',
  'MBTO',
  'MIDI',
  'MLBI',
  'MLPL',
  'MPPA',
  'MRAT',
  'MYOR',
  'PSDN',
  'RANC',
  'ROTI',
  'SDPC',
  'SGRO',
  'SIMP',
  'SIPD',
  'SKBM',
  'SKLT',
  'SMAR',
  'SSMS',
  'STTP',
  'TBLA',
  'TCID',
  'TGKA',
  'ULTJ',
  'UNSP',
  'UNVR',
  'WAPO',
  'WICO',
  'WIIM',
  'DAYA',
  'DPUM',
  'KINO',
  'CLEO',
  'HOKI',
  'CAMP',
  'PCAR',
  'MGRO',
  'ANDI',
  'GOOD',
  'FOOD',
  'BEEF',
  'COCO',
  'ITIC',
  'KEJU',
  'PSGO',
  'AGAR',
  'UCID'],
 'energi': ['ABMM',
  'AKRA',
  'APEX',
  'ARII',
  'ARTI',
  'BBRM',
  'BIPI',
  'BSSR',
  'BULL',
  'BUMI',
  'BYAN',
  'CANI',
  'CNKO',
  'DEWA',
  'DOID',
  'DSSA',
  'ELSA',
  'ENRG',
  'GEMS',
  'GTBO',
  'HITS',
  'HRUM',
  'IATA',
  'INDY',
  'ITMA',
  'ITMG',
  'KKGI',
  'KOPI',
  'LEAD',
  'MBAP',
  'MBSS',
  'MEDC',
  'MTFN',
  'MYOH',
  'PGAS',
  'PKPK',
  'PTBA',
  'PTIS',
  'PTRO',
  'RAJA',
  'RIGS',
  'RUIS',
  'SMMT',
  'SMRU',
  'SOCI',
  'SUGI',
  'TOBA',
  'TPMA',
  'TRAM',
  'WINS',
  'SHIP',
  'TAMU',
  'FIRE',
  'PSSI',
  'DWGL',
  'BOSS',
  'JSKY',
  'INPS',
  'TCPI',
  'SURE',
  'WOWS',
  'TEBE',
  'ADRO',
  'AIMS'],
 'industrial': ['AMFG',
  'AMIN',
  'APII',
  'ARNA',
  'ASGR',
  'ASII',
  'BHIT',
  'BNBR',
  'CTTH',
  'DYAN',
  'HEXA',
  'IBFN',
  'ICON',
  'IKAI',
  'IKBI',
  'IMPC',
  'INDX',
  'INTA',
  'JECC',
  'JTPE',
  'KBLI',
  'KBLM',
  'KIAS',
  'KOBX',
  'KOIN',
  'KONI',
  'LION',
  'MDRN',
  'MFMI',
  'MLIA',
  'SCCO',
  'TIRA',
  'TOTO',
  'TRIL',
  'UNTR',
  'VOKS',
  'ZBRA',
  'MARK',
  'SPTO',
  'SKRN',
  'CAKK',
  'SOSS',
  'CCSI',
  'BLUE',
  'ARKA',
  'SINI'],
 'infrastruktur': ['ACST',
  'ADHI',
  'BALI',
  'BTEL',
  'BUKK',
  'CASS',
  'CENT',
  'CMNP',
  'DGIK',
  'EXCL',
  'GOLD',
  'HADE',
  'IBST',
  'ISAT',
  'JKON',
  'JSMR',
  'KARW',
  'KBLV',
  'LINK',
  'META',
  'NRCA',
  'PTPP',
  'SSIA',
  'SUPR',
  'TBIG',
  'TLKM',
  'TOTL',
  'TOWR',
  'WIKA',
  'WSKT',
  'IDPR',
  'MTRA',
  'OASA',
  'POWR',
  'PBSA',
  'PORT',
  'TGRA',
  'TOPS',
  'MPOW',
  'GMFI',
  'PPRE',
  'WEGE',
  'IPCM',
  'LCKM',
  'GHON',
  'IPCC',
  'MTPS',
  'JAST',
  'KEEN'],
 'kesehatan': ['DVLA',
  'INAF',
  'KAEF',
  'KLBF',
  'MERK',
  'MIKA',
  'PYFA',
  'SAME',
  'SCPI',
  'SIDO',
  'SILO',
  'SRAJ',
  'TSPC',
  'PRDA',
  'PRIM',
  'HEAL',
  'PEHA',
  'IRRA'],
 'keuangan': ['ABDA',
  'AMAG',
  'APIC',
  'ARTO',
  'ASBI',
  'ASDM',
  'ASJT',
  'ASMI',
  'ASRM',
  'BABP',
  'BACA',
  'BBCA',
  'BBHI',
  'BBKP',
  'BBLD',
  'BBMD',
  'BBNI',
  'BBRI',
  'BBTN',
  'BBYB',
  'BCAP',
  'BCIC',
  'BDMN',
  'BEKS',
  'BFIN',
  'BGTG',
  'BINA',
  'BJBR',
  'BJTM',
  'BKSW',
  'BMAS',
  'BMRI',
  'BNBA',
  'BNGA',
  'BNII',
  'BNLI',
  'BPFI',
  'BPII',
  'BSIM',
  'BSWD',
  'BTPN',
  'BVIC',
  'CFIN',
  'DEFI',
  'DNAR',
  'DNET',
  'GSMF',
  'HDFA',
  'INPC',
  'LPGI',
  'LPPS',
  'MAYA',
  'MCOR',
  'MEGA',
  'MREI',
  'NISP',
  'NOBU',
  'OCAP',
  'PADI',
  'PALM',
  'PANS',
  'PEGE',
  'PLAS',
  'PNBN',
  'PNBS',
  'PNIN',
  'PNLF',
  'RELI',
  'SDRA',
  'SMMA',
  'SRTG',
  'STAR',
  'TIFA',
  'TRIM',
  'TRUS',
  'VICO',
  'VINS',
  'VRNA',
  'WOMF',
  'YULE',
  'CASA',
  'BRIS',
  'MTWI',
  'JMAS',
  'NICK',
  'BTPS',
  'TUGU',
  'POLA',
  'SFAN',
  'LIFE',
  'FUJI',
  'ADMF',
  'AGRO',
  'AGRS',
  'AHAP',
  'POOL'],
 'properti': ['APLN',
  'ASRI',
  'BAPA',
  'BCIP',
  'BEST',
  'BIKA',
  'BIPP',
  'BKDP',
  'BKSL',
  'BSDE',
  'COWL',
  'CTRA',
  'DART',
  'DILD',
  'DMAS',
  'DUTI',
  'ELTY',
  'EMDE',
  'FMII',
  'GAMA',
  'GMTD',
  'GPRA',
  'INPP',
  'JRPT',
  'KIJA',
  'LCGP',
  'LPCK',
  'LPKR',
  'LPLI',
  'MDLN',
  'MKPI',
  'MMLP',
  'MTLA',
  'MTSM',
  'NIRO',
  'OMRE',
  'PLIN',
  'PUDP',
  'PWON',
  'RBMS',
  'RDTX',
  'RIMO',
  'RODA',
  'SMDM',
  'SMRA',
  'TARA',
  'CSIS',
  'ARMY',
  'NASA',
  'RISE',
  'POLL',
  'LAND',
  'PANI',
  'CITY',
  'MPRO',
  'SATU',
  'URBN',
  'POLI',
  'CPRI',
  'POSA',
  'PAMG',
  'BAPI',
  'NZIA',
  'REAL',
  'PPRO'],
 'teknologi': ['ATIC',
  'EMTK',
  'KREN',
  'LMAS',
  'MLPT',
  'MTDL',
  'PTSN',
  'SKYB',
  'KIOS',
  'MCAS',
  'NFCX',
  'DIVA',
  'LUCK',
  'ENVY',
  'HDIT',
  'TFAS',
  'DMMX',
  'GLVA'],
 'transportasi_dan_logistik': ['AKSI',
  'ASSA',
  'BIRD',
  'BLTA',
  'CMPP',
  'GIAA',
  'IMJS',
  'LRNA',
  'MIRA',
  'MITI',
  'NELY',
  'SAFE',
  'SDMU',
  'SMDR',
  'TAXI',
  'TMAS',
  'WEHA',
  'HELI',
  'TRUK',
  'TNCA',
  'BPTR',
  'SAPX',
  'DEAL',
  'JAYA',
  'KJEN']}

## Data Load From YFinance

In [55]:
"""
Filter saham IDX aktif
Pakai download satu per satu dengan fallback minimal
"""

import yfinance as yf
import pandas as pd
import time
import random

sektor = terkelompok

# ─── DATE RANGES ──────────────────────────────────────────────────────────────
data_start  = "2021-06-01"
data_end    = "2026-01-01"
train_start = "2022-01-01"
train_end   = "2023-12-31"
test_start  = "2024-01-01"
test_end    = "2025-12-31"

STAGNANT_DAYS = 21   # ~1 bulan hari bursa (Batas maksimal harga boleh beku)
MIN_DATA      = 50   # Minimal riwayat data (baris)
STAGNANT_CAL  = 35   # ~1 bulan kalender (Toleransi gap dari 31 Des 2023)

all_tickers = [t for lst in sektor.values() for t in lst]
ticker_to_sektor = {t: s for s, lst in sektor.items() for t in lst}

print(f"Total ticker: {len(all_tickers)}")
print("Download satu per satu (filter stagnan 1 bulan)...\n")

aktif   = []
dibuang = []
errors  = []
hist_dict = {}

# PROSES FILTERING
for i, ticker in enumerate(all_tickers):
    sym = ticker + ".JK"
    try:
        # Download keseluruhan data 2020-2025
        hist = yf.download(sym, start="2020-01-01", end="2025-12-31",
                           multi_level_index=False, auto_adjust=False, progress=False)

        # Filtering hanya pakai data close sampai akhir 2023
        hist_filter = hist.loc[:"2023-12-31"]

        close = hist_filter["Close"].dropna() if not hist_filter.empty else pd.Series(dtype=float)

        stagnant = False
        alasan = ""

        if len(close) < MIN_DATA:
            stagnant = True
            alasan = f"data kurang ({len(close)} titik)"
        else:
            # Patokan di akhir tahun 2023
            tanggal_patokan = pd.Timestamp("2023-12-31")

            last_date = close.index[-1]
            if hasattr(last_date, 'tzinfo') and last_date.tzinfo is not None:
                last_date = last_date.tz_convert(None)

            gap = (tanggal_patokan - last_date).days

            if gap > STAGNANT_CAL:
                stagnant = True
                alasan = f"tidak ada transaksi {gap} hari (dari 31 Des 2023)"
            else:
                # Cek apakah pernah suspend/beku > 1 bulan di riwayatnya
                roll_std = close.rolling(STAGNANT_DAYS).std()
                if (roll_std == 0).any():
                    stagnant = True
                    alasan = "pernah suspend/harga beku > 1 bulan"

        if stagnant:
            dibuang.append((ticker, alasan))
        else:
            aktif.append(ticker)
            hist_dict[ticker] = hist

        status = "❌ dibuang" if stagnant else "✅ aktif"
        print(f"  [{i+1:>3}/{len(all_tickers)}] {ticker:<6} {status} {alasan}")

    except Exception as e:
        errors.append(ticker)
        print(f"  [{i+1:>3}/{len(all_tickers)}] {ticker:<6} ⚠️  error: {str(e)[:60]}")

    time.sleep(random.uniform(0.3, 0.7))

# ─── OUTPUT ────────────────────────────────────────────────────
aktif_set = set(aktif)
sektor_bersih = {s: [t for t in lst if t in aktif_set]
                 for s, lst in sektor.items()
                 if any(t in aktif_set for t in lst)}

print("\n" + "="*55)
print(f"  TOTAL SEMULA  : {len(all_tickers)}")
print(f"  AKTIF         : {len(aktif)}")
print(f"  DIBUANG       : {len(dibuang)}")
print(f"  ERROR         : {len(errors)}")
print("="*55)

for s, lst in sektor_bersih.items():
    print(f"  {s:<30} {len(lst):>3} / {len(sektor[s])}")

Total ticker: 646
Download satu per satu (filter stagnan 1 bulan)...

  [  1/646] AKPI   ✅ aktif
  [  2/646] ALDO   ✅ aktif
  [  3/646] ALKA   ✅ aktif
  [  4/646] ALMI   ✅ aktif
  [  5/646] ANTM   ✅ aktif
  [  6/646] APLI   ✅ aktif
  [  7/646] BAJA   ✅ aktif
  [  8/646] BMSR   ✅ aktif
  [  9/646] BRMS   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 10/646] BRNA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 11/646] BRPT   ✅ aktif
  [ 12/646] BTON   ✅ aktif
  [ 13/646] CITA   ✅ aktif
  [ 14/646] CLPI   ✅ aktif
  [ 15/646] CTBN   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 16/646] DKFT   ✅ aktif
  [ 17/646] DPNS   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 18/646] EKAD   ✅ aktif
  [ 19/646] ESSA   ✅ aktif
  [ 20/646] ETWA   ✅ aktif
  [ 21/646] FASW   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 22/646] FPNI   ✅ aktif
  [ 23/646] GDST   ✅ aktif
  [ 24/646] IGAR   ✅ aktif
  [ 25/646] INAI   ✅ aktif
  [ 26/646] INCI   ✅ aktif
  [ 27/646] INCO   ✅ aktif
  [ 28/646] INKP   ✅ aktif
  [ 29/646] INRU   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 30/646] INTD   ✅ aktif
  [ 31/646] INTP   ✅ aktif
  [ 32/646] IPOL   ✅ aktif
  [ 33/646] ISSP   ✅ aktif
  [ 34/646] KBRI   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 35/646] KDSI   ✅ aktif
  [ 36/646] KRAS   ✅ aktif
  [ 37/646] LMSH   ✅ aktif
  [ 38/646] LTLS   ✅ aktif
  [ 39/646] MDKA   ✅ aktif
  [ 40/646] NIKL   ✅ aktif
  [ 41/646] OKAS   ✅ aktif
  [ 42/646] PICO   ✅ aktif
  [ 43/646] PSAB   ✅ aktif
  [ 44/646] SIMA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 45/646] SMBR   ✅ aktif
  [ 46/646] SMCB   ✅ aktif
  [ 47/646] SMGR   ✅ aktif
  [ 48/646] SPMA   ✅ aktif
  [ 49/646] SQMI   ✅ aktif
  [ 50/646] SRSN   ✅ aktif
  [ 51/646] SULI   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 52/646] TALF   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 53/646] TBMS   ✅ aktif
  [ 54/646] TINS   ✅ aktif
  [ 55/646] TIRT   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 56/646] TKIM   ✅ aktif
  [ 57/646] TPIA   ✅ aktif
  [ 58/646] TRST   ✅ aktif
  [ 59/646] UNIC   ✅ aktif
  [ 60/646] WTON   ✅ aktif
  [ 61/646] YPAS   ✅ aktif
  [ 62/646] INCF   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 63/646] WSBP   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 64/646] KMTR   ✅ aktif
  [ 65/646] MDKI   ✅ aktif
  [ 66/646] ZINC   ✅ aktif
  [ 67/646] PBID   ✅ aktif
  [ 68/646] TDPM   ✅ aktif
  [ 69/646] SWAT   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 70/646] MOLI   ✅ aktif
  [ 71/646] HKMU   ✅ aktif
  [ 72/646] KAYU   ✅ aktif
  [ 73/646] SMKL   ✅ aktif
  [ 74/646] GGRP   ✅ aktif
  [ 75/646] OPMS   ✅ aktif
  [ 76/646] PURE   ✅ aktif
  [ 77/646] ESIP   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 78/646] IFSH   ✅ aktif
  [ 79/646] IFII   ✅ aktif
  [ 80/646] ADMG   ✅ aktif
  [ 81/646] AGII   ✅ aktif
  [ 82/646] ABBA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 83/646] ACES   ✅ aktif
  [ 84/646] AKKU   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 85/646] ARGO   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 86/646] ARTA   ✅ aktif
  [ 87/646] AUTO   ✅ aktif
  [ 88/646] BATA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 89/646] BAYU   ✅ aktif
  [ 90/646] BIMA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 91/646] BLTZ   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 92/646] BMTR   ✅ aktif
  [ 93/646] BOLT   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 94/646] BRAM   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 95/646] BUVA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [ 96/646] CINT   ✅ aktif
  [ 97/646] CNTX   ✅ aktif
  [ 98/646] CSAP   ✅ aktif
  [ 99/646] ECII   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [100/646] ERAA   ✅ aktif
  [101/646] ERTX   ✅ aktif
  [102/646] ESTI   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [103/646] FAST   ✅ aktif
  [104/646] FORU   ✅ aktif
  [105/646] GDYR   ✅ aktif
  [106/646] GEMA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [107/646] GJTL   ✅ aktif
  [108/646] GLOB   ✅ aktif
  [109/646] GWSA   ✅ aktif
  [110/646] HOME   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [111/646] HOTL   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [112/646] IIKP   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [113/646] IMAS   ✅ aktif
  [114/646] INDR   ✅ aktif
  [115/646] INDS   ✅ aktif
  [116/646] JIHD   ✅ aktif
  [117/646] JSPT   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [118/646] KICI   ✅ aktif
  [119/646] KPIG   ✅ aktif
  [120/646] LMPI   ✅ aktif
  [121/646] LPIN   ✅ aktif
  [122/646] LPPF   ✅ aktif
  [123/646] MAPI   ✅ aktif
  [124/646] MDIA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [125/646] MGNA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [126/646] MICE   ✅ aktif
  [127/646] MNCN   ✅ aktif
  [128/646] MPMX   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [129/646] MSKY   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [130/646] MYTX   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [131/646] PANR   ✅ aktif
  [132/646] PBRX   ✅ aktif
  [133/646] PDES   ✅ aktif
  [134/646] PGLI   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [135/646] PJAA   ✅ aktif
  [136/646] PSKT   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [137/646] PTSP   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [138/646] RALS   ✅ aktif
  [139/646] RICY   ✅ aktif
  [140/646] SCMA   ✅ aktif
  [141/646] SHID   ✅ aktif
  [142/646] SMSM   ✅ aktif
  [143/646] SONA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [144/646] SRIL   ✅ aktif
  [145/646] SSTM   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [146/646] TELE   ✅ aktif
  [147/646] TFCO   ✅ aktif
  [148/646] TMPO   ✅ aktif
  [149/646] TRIO   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [150/646] TRIS   ✅ aktif
  [151/646] UNIT   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [152/646] VIVA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [153/646] JGLE   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [154/646] MARI   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [155/646] MKNT   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [156/646] BOGA   ✅ aktif
  [157/646] CARS   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [158/646] MINA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [159/646] MAPB   ✅ aktif
  [160/646] WOOD   ✅ aktif
  [161/646] HRTA   ✅ aktif
  [162/646] MABA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [163/646] BELL   ✅ aktif
  [164/646] DFAM   ✅ aktif
  [165/646] PZZA   ✅ aktif
  [166/646] MSIN   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [167/646] MAPA   ✅ aktif
  [168/646] NUSA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [169/646] FILM   ✅ aktif
  [170/646] DIGI   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [171/646] DUCK   ✅ aktif
  [172/646] YELO   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [173/646] SOTS   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [174/646] ZONE   ✅ aktif
  [175/646] CLAY   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [176/646] NATO   ✅ aktif
  [177/646] HRME   ✅ aktif
  [178/646] FITT   ✅ aktif
  [179/646] BOLA   ✅ aktif
  [180/646] POLU   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [181/646] IPTV   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [182/646] EAST   ✅ aktif
  [183/646] KOTA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [184/646] INOV   ✅ aktif
  [185/646] SLIS   ✅ aktif
  [186/646] PMJS   ✅ aktif
  [187/646] PNSE   ✅ aktif
  [188/646] POLY   ✅ aktif
  [189/646] AALI   ✅ aktif
  [190/646] ADES   ✅ aktif
  [191/646] AISA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [192/646] ALTO   ✅ aktif
  [193/646] AMRT   ✅ aktif
  [194/646] ANJT   ✅ aktif
  [195/646] BISI   ✅ aktif
  [196/646] BTEK   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [197/646] BUDI   ✅ aktif
  [198/646] BWPT   ✅ aktif
  [199/646] CEKA   ✅ aktif
  [200/646] CPIN   ✅ aktif
  [201/646] CPRO   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [202/646] DLTA   ✅ aktif
  [203/646] DSFI   ✅ aktif
  [204/646] DSNG   ✅ aktif
  [205/646] EPMT   ✅ aktif
  [206/646] FISH   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [207/646] GGRM   ✅ aktif
  [208/646] GOLL   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [209/646] GZCO   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [210/646] HERO   ✅ aktif
  [211/646] HMSP   ✅ aktif
  [212/646] ICBP   ✅ aktif
  [213/646] INDF   ✅ aktif
  [214/646] JAWA   ✅ aktif
  [215/646] JPFA   ✅ aktif
  [216/646] LAPD   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [217/646] LSIP   ✅ aktif
  [218/646] MAGP   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [219/646] MAIN   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [220/646] MBTO   ✅ aktif
  [221/646] MIDI   ✅ aktif
  [222/646] MLBI   ✅ aktif
  [223/646] MLPL   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [224/646] MPPA   ✅ aktif
  [225/646] MRAT   ✅ aktif
  [226/646] MYOR   ✅ aktif
  [227/646] PSDN   ✅ aktif
  [228/646] RANC   ✅ aktif
  [229/646] ROTI   ✅ aktif
  [230/646] SDPC   ✅ aktif
  [231/646] SGRO   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [232/646] SIMP   ✅ aktif
  [233/646] SIPD   ✅ aktif
  [234/646] SKBM   ✅ aktif
  [235/646] SKLT   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [236/646] SMAR   ✅ aktif
  [237/646] SSMS   ✅ aktif
  [238/646] STTP   ✅ aktif
  [239/646] TBLA   ✅ aktif
  [240/646] TCID   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [241/646] TGKA   ✅ aktif
  [242/646] ULTJ   ✅ aktif
  [243/646] UNSP   ✅ aktif
  [244/646] UNVR   ✅ aktif
  [245/646] WAPO   ✅ aktif
  [246/646] WICO   ✅ aktif
  [247/646] WIIM   ✅ aktif
  [248/646] DAYA   ✅ aktif
  [249/646] DPUM   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [250/646] KINO   ✅ aktif
  [251/646] CLEO   ✅ aktif
  [252/646] HOKI   ✅ aktif
  [253/646] CAMP   ✅ aktif
  [254/646] PCAR   ✅ aktif
  [255/646] MGRO   ✅ aktif
  [256/646] ANDI   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [257/646] GOOD   ✅ aktif
  [258/646] FOOD   ✅ aktif
  [259/646] BEEF   ✅ aktif
  [260/646] COCO   ✅ aktif
  [261/646] ITIC   ✅ aktif
  [262/646] KEJU   ✅ aktif
  [263/646] PSGO   ✅ aktif
  [264/646] AGAR   ✅ aktif
  [265/646] UCID   ✅ aktif
  [266/646] ABMM   ✅ aktif
  [267/646] AKRA   ✅ aktif
  [268/646] APEX   ✅ aktif
  [269/646] ARII   ✅ aktif
  [270/646] ARTI   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [271/646] BBRM   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [272/646] BIPI   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [273/646] BSSR   ✅ aktif
  [274/646] BULL   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [275/646] BUMI   ✅ aktif
  [276/646] BYAN   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [277/646] CANI   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [278/646] CNKO   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [279/646] DEWA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [280/646] DOID   ✅ aktif
  [281/646] DSSA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [282/646] ELSA   ✅ aktif
  [283/646] ENRG   ✅ aktif
  [284/646] GEMS   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [285/646] GTBO   ✅ aktif
  [286/646] HITS   ✅ aktif
  [287/646] HRUM   ✅ aktif
  [288/646] IATA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [289/646] INDY   ✅ aktif
  [290/646] ITMA   ✅ aktif
  [291/646] ITMG   ✅ aktif
  [292/646] KKGI   ✅ aktif
  [293/646] KOPI   ✅ aktif
  [294/646] LEAD   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [295/646] MBAP   ✅ aktif
  [296/646] MBSS   ✅ aktif
  [297/646] MEDC   ✅ aktif
  [298/646] MTFN   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [299/646] MYOH   ✅ aktif
  [300/646] PGAS   ✅ aktif
  [301/646] PKPK   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [302/646] PTBA   ✅ aktif
  [303/646] PTIS   ✅ aktif
  [304/646] PTRO   ✅ aktif
  [305/646] RAJA   ✅ aktif
  [306/646] RIGS   ✅ aktif
  [307/646] RUIS   ✅ aktif
  [308/646] SMMT   ✅ aktif
  [309/646] SMRU   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [310/646] SOCI   ✅ aktif
  [311/646] SUGI   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [312/646] TOBA   ✅ aktif
  [313/646] TPMA   ✅ aktif
  [314/646] TRAM   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [315/646] WINS   ✅ aktif
  [316/646] SHIP   ✅ aktif
  [317/646] TAMU   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [318/646] FIRE   ✅ aktif
  [319/646] PSSI   ✅ aktif
  [320/646] DWGL   ✅ aktif
  [321/646] BOSS   ✅ aktif
  [322/646] JSKY   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [323/646] INPS   ✅ aktif
  [324/646] TCPI   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [325/646] SURE   ✅ aktif
  [326/646] WOWS   ✅ aktif
  [327/646] TEBE   ✅ aktif
  [328/646] ADRO   ✅ aktif
  [329/646] AIMS   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [330/646] AMFG   ✅ aktif
  [331/646] AMIN   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [332/646] APII   ✅ aktif
  [333/646] ARNA   ✅ aktif
  [334/646] ASGR   ✅ aktif
  [335/646] ASII   ✅ aktif
  [336/646] BHIT   ✅ aktif
  [337/646] BNBR   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [338/646] CTTH   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [339/646] DYAN   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [340/646] HEXA   ✅ aktif
  [341/646] IBFN   ✅ aktif
  [342/646] ICON   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [343/646] IKAI   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [344/646] IKBI   ✅ aktif
  [345/646] IMPC   ✅ aktif
  [346/646] INDX   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [347/646] INTA   ✅ aktif
  [348/646] JECC   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [349/646] JTPE   ✅ aktif
  [350/646] KBLI   ✅ aktif
  [351/646] KBLM   ✅ aktif
  [352/646] KIAS   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [353/646] KOBX   ✅ aktif
  [354/646] KOIN   ✅ aktif
  [355/646] KONI   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [356/646] LION   ✅ aktif
  [357/646] MDRN   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [358/646] MFMI   ✅ aktif
  [359/646] MLIA   ✅ aktif
  [360/646] SCCO   ✅ aktif
  [361/646] TIRA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [362/646] TOTO   ✅ aktif
  [363/646] TRIL   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [364/646] UNTR   ✅ aktif
  [365/646] VOKS   ✅ aktif
  [366/646] ZBRA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [367/646] MARK   ✅ aktif
  [368/646] SPTO   ✅ aktif
  [369/646] SKRN   ✅ aktif
  [370/646] CAKK   ✅ aktif
  [371/646] SOSS   ✅ aktif
  [372/646] CCSI   ✅ aktif
  [373/646] BLUE   ✅ aktif
  [374/646] ARKA   ✅ aktif
  [375/646] SINI   ✅ aktif
  [376/646] ACST   ✅ aktif
  [377/646] ADHI   ✅ aktif
  [378/646] BALI   ✅ aktif
  [379/646] BTEL   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [380/646] BUKK   ✅ aktif
  [381/646] CASS   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [382/646] CENT   ✅ aktif
  [383/646] CMNP   ✅ aktif
  [384/646] DGIK   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [385/646] EXCL   ✅ aktif
  [386/646] GOLD   ✅ aktif
  [387/646] HADE   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [388/646] IBST   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [389/646] ISAT   ✅ aktif
  [390/646] JKON   ✅ aktif
  [391/646] JSMR   ✅ aktif
  [392/646] KARW   ✅ aktif
  [393/646] KBLV   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [394/646] LINK   ✅ aktif
  [395/646] META   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [396/646] NRCA   ✅ aktif
  [397/646] PTPP   ✅ aktif
  [398/646] SSIA   ✅ aktif
  [399/646] SUPR   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [400/646] TBIG   ✅ aktif
  [401/646] TLKM   ✅ aktif
  [402/646] TOTL   ✅ aktif
  [403/646] TOWR   ✅ aktif
  [404/646] WIKA   ✅ aktif
  [405/646] WSKT   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [406/646] IDPR   ✅ aktif
  [407/646] MTRA   ✅ aktif
  [408/646] OASA   ✅ aktif
  [409/646] POWR   ✅ aktif
  [410/646] PBSA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [411/646] PORT   ✅ aktif
  [412/646] TGRA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [413/646] TOPS   ✅ aktif
  [414/646] MPOW   ✅ aktif
  [415/646] GMFI   ✅ aktif
  [416/646] PPRE   ✅ aktif
  [417/646] WEGE   ✅ aktif
  [418/646] IPCM   ✅ aktif
  [419/646] LCKM   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [420/646] GHON   ✅ aktif
  [421/646] IPCC   ✅ aktif
  [422/646] MTPS   ✅ aktif
  [423/646] JAST   ✅ aktif
  [424/646] KEEN   ✅ aktif
  [425/646] DVLA   ✅ aktif
  [426/646] INAF   ✅ aktif
  [427/646] KAEF   ✅ aktif
  [428/646] KLBF   ✅ aktif
  [429/646] MERK   ✅ aktif
  [430/646] MIKA   ✅ aktif
  [431/646] PYFA   ✅ aktif
  [432/646] SAME   ✅ aktif
  [433/646] SCPI   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [434/646] SIDO   ✅ aktif
  [435/646] SILO   ✅ aktif
  [436/646] SRAJ   ✅ aktif
  [437/646] TSPC   ✅ aktif
  [438/646] PRDA   ✅ aktif
  [439/646] PRIM   ✅ aktif
  [440/646] HEAL   ✅ aktif
  [441/646] PEHA   ✅ aktif
  [442/646] IRRA   ✅ aktif
  [443/646] ABDA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [444/646] AMAG   ✅ aktif
  [445/646] APIC   ✅ aktif
  [446/646] ARTO   ✅ aktif
  [447/646] ASBI   ✅ aktif
  [448/646] ASDM   ✅ aktif
  [449/646] ASJT   ✅ aktif
  [450/646] ASMI   ✅ aktif
  [451/646] ASRM   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [452/646] BABP   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [453/646] BACA   ✅ aktif
  [454/646] BBCA   ✅ aktif
  [455/646] BBHI   ✅ aktif
  [456/646] BBKP   ✅ aktif
  [457/646] BBLD   ✅ aktif
  [458/646] BBMD   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [459/646] BBNI   ✅ aktif
  [460/646] BBRI   ✅ aktif
  [461/646] BBTN   ✅ aktif
  [462/646] BBYB   ✅ aktif
  [463/646] BCAP   ✅ aktif
  [464/646] BCIC   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [465/646] BDMN   ✅ aktif
  [466/646] BEKS   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [467/646] BFIN   ✅ aktif
  [468/646] BGTG   ✅ aktif
  [469/646] BINA   ✅ aktif
  [470/646] BJBR   ✅ aktif
  [471/646] BJTM   ✅ aktif
  [472/646] BKSW   ✅ aktif
  [473/646] BMAS   ✅ aktif
  [474/646] BMRI   ✅ aktif
  [475/646] BNBA   ✅ aktif
  [476/646] BNGA   ✅ aktif
  [477/646] BNII   ✅ aktif
  [478/646] BNLI   ✅ aktif
  [479/646] BPFI   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [480/646] BPII   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [481/646] BSIM   ✅ aktif
  [482/646] BSWD   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [483/646] BTPN   ✅ aktif
  [484/646] BVIC   ✅ aktif
  [485/646] CFIN   ✅ aktif
  [486/646] DEFI   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [487/646] DNAR   ✅ aktif
  [488/646] DNET   ✅ aktif
  [489/646] GSMF   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [490/646] HDFA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [491/646] INPC   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [492/646] LPGI   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [493/646] LPPS   ✅ aktif
  [494/646] MAYA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [495/646] MCOR   ✅ aktif
  [496/646] MEGA   ✅ aktif
  [497/646] MREI   ✅ aktif
  [498/646] NISP   ✅ aktif
  [499/646] NOBU   ✅ aktif
  [500/646] OCAP   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [501/646] PADI   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [502/646] PALM   ✅ aktif
  [503/646] PANS   ✅ aktif
  [504/646] PEGE   ✅ aktif
  [505/646] PLAS   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [506/646] PNBN   ✅ aktif
  [507/646] PNBS   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [508/646] PNIN   ✅ aktif
  [509/646] PNLF   ✅ aktif
  [510/646] RELI   ✅ aktif
  [511/646] SDRA   ✅ aktif
  [512/646] SMMA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [513/646] SRTG   ✅ aktif
  [514/646] STAR   ✅ aktif
  [515/646] TIFA   ✅ aktif
  [516/646] TRIM   ✅ aktif
  [517/646] TRUS   ✅ aktif
  [518/646] VICO   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [519/646] VINS   ✅ aktif
  [520/646] VRNA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [521/646] WOMF   ✅ aktif
  [522/646] YULE   ✅ aktif
  [523/646] CASA   ✅ aktif
  [524/646] BRIS   ✅ aktif
  [525/646] MTWI   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [526/646] JMAS   ✅ aktif
  [527/646] NICK   ✅ aktif
  [528/646] BTPS   ✅ aktif
  [529/646] TUGU   ✅ aktif
  [530/646] POLA   ❌ dibuang pernah suspend/harga beku > 1 bulan
  [531/646] SFAN   ✅ aktif

In [56]:
for s, lst in sektor_bersih.items():
    print(f"{s} → {len(lst)} saham")

barang_baku → 66 saham
barang_konsumsi_non_primer → 63 saham
barang_konsumsi_primer → 62 saham
energi → 43 saham
industrial → 32 saham
infrastruktur → 37 saham
kesehatan → 17 saham
keuangan → 68 saham
properti → 30 saham
teknologi → 15 saham
transportasi_dan_logistik → 15 saham

In [57]:
import os
os.makedirs("data_saham", exist_ok=True)

for ticker, df_hist in hist_dict.items():
    df_hist.to_csv(f"data_saham/{ticker}.csv")

print(f"\nCSV tersimpan: {len(hist_dict)} file di folder 'data_saham/'")

CSV tersimpan: 448 file di folder 'data_saham/'

In [58]:
import pandas as pd
import os

# ─── LOAD CSV → SUSUN all_df PER SEKTOR ───────────────────────
all_df = {}

for sektor, tickers in sektor_bersih.items():
    frames = {}
    for ticker in tickers:
        path = f"data_saham/{ticker}.csv"
        if os.path.exists(path):
            df_ticker = pd.read_csv(path, index_col=0, parse_dates=True)
            frames[ticker] = df_ticker["Close"]

    if frames:
        all_df[sektor] = pd.DataFrame(frames)

for sektor, df in all_df.items():
    print(sektor, "→", df.shape)

# ─── ALIGNMENT ────────────────────────────────────────────────
aligned_df = {}

for sektor, df_sektor in all_df.items():
    df_aligned = df_sektor.dropna()
    aligned_df[sektor] = df_aligned
    print(sektor, df_sektor.shape, "→", df_aligned.shape)

# ─── CLEANING: FILTER MISSING < 5% ───────────────────────────
cleaned_df = {}

for sektor, df_sektor in all_df.items():
    missing_ratio = df_sektor.isna().mean()
    saham_valid = missing_ratio[missing_ratio < 0.05].index
    df_filtered = df_sektor[saham_valid]
    cleaned_df[sektor] = df_filtered
    print(sektor, "→", df_filtered.shape)

for sektor in cleaned_df:
    cleaned_df[sektor] = cleaned_df[sektor].dropna()

# ─── FILTER SAHAM STAGNANT (STD = 0) ─────────────────────────
for sektor, df_sektor in cleaned_df.items():
    std = df_sektor.std()
    saham_aktif = std[std > 0].index
    cleaned_df[sektor] = df_sektor[saham_aktif]

# ─── RINGKASAN ────────────────────────────────────────────────
for sektor, df_sektor in cleaned_df.items():
    print(sektor, df_sektor.shape[1])

total_saham = sum(df.shape[1] for df in cleaned_df.values())
print("Total saham:", total_saham)

total_awal  = sum(df.shape[1] for df in all_df.values())
total_akhir = sum(df.shape[1] for df in cleaned_df.values())

print("Total awal:", total_awal)
print("Total akhir:", total_akhir)
print("Total dihapus:", total_awal - total_akhir)

cleaned_df

barang_baku → (1447, 66)
barang_konsumsi_non_primer → (1447, 63)
barang_konsumsi_primer → (1447, 62)
energi → (1447, 43)
industrial → (1447, 32)
infrastruktur → (1447, 37)
kesehatan → (1447, 17)
keuangan → (1447, 68)
properti → (1447, 30)
teknologi → (1447, 15)
transportasi_dan_logistik → (1447, 15)
barang_baku (1447, 66) → (1447, 66)
barang_konsumsi_non_primer (1447, 63) → (1447, 63)
barang_konsumsi_primer (1447, 62) → (1447, 62)
energi (1447, 43) → (1447, 43)
industrial (1447, 32) → (1447, 32)
infrastruktur (1447, 37) → (1447, 37)
kesehatan (1447, 17) → (1447, 17)
keuangan (1447, 68) → (1447, 68)
properti (1447, 30) → (1447, 30)
teknologi (1447, 15) → (1447, 15)
transportasi_dan_logistik (1447, 15) → (1447, 15)
barang_baku → (1447, 66)
barang_konsumsi_non_primer → (1447, 63)
barang_konsumsi_primer → (1447, 62)
energi → (1447, 43)
industrial → (1447, 32)
infrastruktur → (1447, 37)
kesehatan → (1447, 17)
keuangan → (1447, 68)
properti → (1447, 30)
teknologi → (1447, 15)
transportasi_dan_logistik → (1447, 15)
barang_baku 66
barang_konsumsi_non_primer 63
barang_konsumsi_primer 62
energi 43
industrial 32
infrastruktur 37
kesehatan 17
keuangan 68
properti 30
teknologi 15
transportasi_dan_logistik 15
Total saham: 448
Total awal: 448
Total akhir: 448
Total dihapus: 0

{'barang_baku':              AKPI        ALDO   ALKA   ALMI    ANTM   APLI   BAJA   BMSR  \
 Date
 2020-01-02  380.0  191.840271  410.0  358.0   840.0  175.0   62.0  106.0
 2020-01-03  410.0  187.044266  418.0  310.0   850.0  170.0   64.0  108.0
 2020-01-06  410.0  191.840271  400.0  310.0   885.0  132.0   64.0  105.0
 2020-01-07  410.0  191.840271  410.0  348.0   875.0  142.0   62.0  106.0
 2020-01-08  410.0  191.840271  410.0  318.0   905.0  139.0   60.0  105.0
 ...           ...         ...    ...    ...     ...    ...    ...    ...
 2025-12-22  560.0  795.000000  364.0   74.0  3190.0  410.0  164.0  318.0
 2025-12-23  570.0  805.000000  358.0   74.0  3190.0  406.0  162.0  326.0
 2025-12-24  555.0  805.000000  360.0   74.0  3220.0  384.0  163.0  318.0
 2025-12-29  570.0  785.000000  366.0   74.0  3300.0  382.0  163.0  316.0
 2025-12-30  570.0  800.000000  366.0   74.0  3150.0  374.0  163.0  312.0

                    BRPT   BTON  ...   HKMU  KAYU   SMKL   GGRP   OPMS   PURE  \
 Date                            ...
 2020-01-02  1456.526978  204.0  ...  256.0  66.0  236.0  386.0  100.0  262.0
 2020-01-03  1416.758301  204.0  ...  256.0  67.0  232.0  384.0   98.0  252.0
 2020-01-06  1297.452393  198.0  ...  256.0  68.0  212.0  384.0   97.0  266.0
 2020-01-07  1317.336670  200.0  ...  270.0  67.0  222.0  394.0  102.0  292.0
 2020-01-08  1272.596924  198.0  ...  238.0  65.0  222.0  396.0   98.0  270.0
 ...                 ...    ...  ...    ...   ...    ...    ...    ...    ...
 2025-12-22  3440.000000  378.0  ...   50.0  18.0  175.0  290.0  122.0   51.0
 2025-12-23  3280.000000  376.0  ...   50.0  18.0  177.0  278.0  122.0   51.0
 2025-12-24  3130.000000  378.0  ...   50.0  18.0  173.0  280.0  120.0   51.0
 2025-12-29  3280.000000  384.0  ...   50.0  18.0  175.0  288.0  156.0   51.0
 2025-12-30  3270.000000  374.0  ...   50.0  18.0  174.0  292.0  135.0   51.0

              IFSH   IFII   ADMG    AGII
 Date
 2020-01-02  645.0  200.0  187.0   650.0
 2020-01-03  580.0  202.0  187.0   645.0
 2020-01-06  580.0  199.0  186.0   645.0
 2020-01-07  580.0  199.0  186.0   625.0
 2020-01-08  560.0  200.0  186.0   620.0
 ...           ...    ...    ...     ...
 2025-12-22  800.0  222.0  186.0  1600.0
 2025-12-23  795.0  224.0  186.0  1550.0
 2025-12-24  785.0  222.0  179.0  1510.0
 2025-12-29  780.0  222.0  181.0  1570.0
 2025-12-30  790.0  220.0  220.0  1515.0

 [1447 rows x 66 columns],
 'barang_konsumsi_non_primer':               ACES    ARTA    AUTO    BAYU   BMTR   CINT   CNTX        CSAP  \
 Date
 2020-01-02  1510.0   450.0  1300.0  1200.0  344.0  278.0  338.0  447.965393
 2020-01-03  1515.0   430.0  1275.0  1210.0  342.0  298.0  338.0  447.965393
 2020-01-06  1470.0   426.0  1260.0  1190.0  336.0  302.0  344.0  443.983490
 2020-01-07  1440.0   422.0  1255.0  1185.0  342.0  300.0  320.0  443.983490
 2020-01-08  1410.0   422.0  1240.0  1000.0  338.0  300.0  346.0  441.992523
 ...            ...     ...     ...     ...    ...    ...    ...         ...
 2025-12-22   414.0  2820.0  2600.0  1385.0  139.0  192.0  142.0  320.000000
 2025-12-23   412.0  2720.0  2600.0  1380.0  139.0  192.0  142.0  314.000000
 2025-12-24   412.0  2890.0  2670.0  1395.0  138.0  179.0  142.0  320.000000
 2025-12-29   412.0  3300.0  2700.0  1375.0  138.0  181.0  142.0  314.000000
 2025-12-30   410.0  3400.0  2690.0  1370.0  139.0  244.0  142.0  316.000000

              ERAA   ERTX  ...    NATO    HRME   FITT   BOLA   EAST   INOV  \
 Date                      ...
 2020-01-02  366.0  136.0  ...  1085.0   880.0   73.0  324.0   92.0  372.0
 2020-01-03  362.0  140.0  ...  1095.0   920.0   72.0  320.0   91.0  362.0
 2020-01-06  345.0  141.0  ...  1100.0   955.0   69.0  308.0   92.0  338.0
 2020-01-07  342.0  142.0  ...  1090.0   965.0   71.0  308.0   95.0  320.0
 2020-01-08  342.0  142.0  ...  1095.0  1005.0   72.0  304.0   97.0  326.0
 ...           ...    ...  ...     ...     ...    ...    ...    ...    ...
 2025-12-22  406.0  212.0  ...   316.0    55.0  540.0  175.0   97.0  129.0
 2025-12-23  408.0  208.0  ...   316.0    55.0  480.0  176.0  111.0  129.0
 2025-12-24  406.0  204.0  ...   316.0    51.0  550.0  171.0  102.0  126.0
 2025-12-29  406.0  212.0  ...   316.0    55.0  570.0  175.0  105.0  127.0
 2025-12-30  408.0  230.0  ...   316.0    55.0  555.0  174.0  105.0  125.0

                    SLIS   PMJS   PNSE  POLY
 Date
 2020-01-02  4257.366699  137.0  332.0  61.0
 2020-01-03  4147.692383  138.0  332.0  61.0
 2020-01-06  4157.662598  133.0  332.0  63.0
 2020-01-07  4197.544434  128.0  332.0  63.0
 2020-01-08  4217.485352  138.0  332.0  63.0
 ...                 ...    ...    ...   ...
 2025-12-22    91.000000  114.0  750.0  26.0
 2025-12-23    93.000000  115.0  755.0  28.0
 2025-12-24    91.000000  114.0  755.0  28.0
 2025-12-29    93.000000  113.0  755.0  27.0
 2025-12-30    93.000000  114.0  740.0  28.0

 [1447 rows x 63 columns],
 'barang_konsumsi_primer':                AALI     ADES   ALTO    AMRT    ANJT    BISI   BUDI   BWPT  \
 Date
 2020-01-02  14025.0   1045.0  398.0   875.0  1000.0  1040.0  102.0  153.0
 2020-01-03  14100.0   1050.0  400.0   865.0   980.0  1050.0  103.0  153.0
 2020-01-06  13500.0   1050.0  400.0   845.0   945.0  1050.0  102.0  146.0
 2020-01-07  13400.0   1065.0  400.0   840.0   945.0  1050.0  103.0  150.0
 2020-01-08  13325.0   1060.0  400.0   855.0   910.0  1045.0  100.0  145.0
 ...             ...      ...    ...     ...     ...     ...    ...    ...
 2025-12-22   7400.0  15350.0   18.0  1965.0  1750.0   870.0  218.0  142.0
 2025-12-23   7475.0  15225.0   18.0  1955.0  1785.0   870.0  218.0  143.0
 2025-12-24   7300.0  15225.0   18.0  1960.0  1785.0   865.0  220.0  140.0
 2025-12-29   7325.0  15275.0   18.0  1955.0  1785.0   870.0  216.0  148.0
 2025-12-30   7375.0  15425.0   18.0  1975.0  1780.0   875.0  214.0  143.0

               CEKA    CPIN  ...   MGRO   GOOD   FOOD        BEEF   COCO  \
 Date                        ...
 2020-01-02  1715.0  6575.0  ...  895.0  302.0  113.0  339.435089  945.0
 2020-01-03  1700.0  6900.0  ...  885.0  302.0  111.0  335.971466  865.0
 2020-01-06  1660.0  6850.0  ...  885.0  302.0  111.0  332.507843  860.0
 2020-01-07  1645.0  7325.0  ...  880.0  303.0  112.0  334.239655  860.0
 2020-01-08  1610.0  7275.0  ...  865.0  302.0  110.0  329.044220  945.0
 ...            ...     ...  ...    ...    ...    ...         ...    ...
 2025-12-22  2450.0  4550.0  ...  760.0  364.0  370.0  434.000000  320.0
 2025-12-23  2400.0  4530.0  ...  755.0  364.0  370.0  436.000000  330.0
 2025-12-24  2410.0  4590.0  ...  755.0  364.0  356.0  410.000000  316.0
 2025-12-29  2410.0  4540.0  ...  745.0  366.0  322.0  490.000000  340.0
 2025-12-30  2410.0  4510.0  ...  750.0  370.0  350.0  456.000000  336.0

               ITIC        KEJU   PSGO   AGAR    UCID
 Date
 2020-01-02  2630.0  249.333328  190.0  392.0  1830.0
 2020-01-03  2540.0  253.333328  193.0  368.0  1870.0
 2020-01-06  2590.0  229.333328  187.0  358.0  1820.0
 2020-01-07  2530.0  229.333328  190.0  370.0  1830.0
 2020-01-08  2610.0  224.000000  183.0  380.0  1800.0
 ...            ...         ...    ...    ...     ...
 2025-12-22   344.0  625.000000  208.0  236.0   418.0
 2025-12-23   340.0  630.000000  206.0  246.0   416.0
 2025-12-24   344.0  630.000000  208.0  234.0   424.0
 2025-12-29   352.0  620.000000  208.0  234.0   422.0
 2025-12-30   360.0  680.000000  208.0  236.0   420.0

 [1447 rows x 62 columns],
 'energi':               ABMM    AKRA   APEX   ARII    BSSR   BUMI   DOID   ELSA    ENRG  \
 Date
 2020-01-02  1530.0   780.0  346.0  715.0  1820.0   66.0  282.0  302.0    50.0
 2020-01-03  1530.0   758.0  346.0  715.0  1840.0   73.0  294.0  316.0    52.0
 2020-01-06  1530.0   728.0  336.0  715.0  1895.0   69.0  294.0  330.0    52.0
 2020-01-07  1530.0   706.0  332.0  715.0  1860.0   69.0  294.0  326.0    51.0
 2020-01-08  1530.0   712.0  340.0  715.0  1820.0   68.0  280.0  326.0    51.0
 ...            ...     ...    ...    ...     ...    ...    ...    ...     ...
 2025-12-22  2800.0  1240.0  230.0  314.0  3960.0  394.0  302.0  492.0  1450.0
 2025-12-23  2780.0  1250.0  226.0  306.0  3950.0  380.0  320.0  494.0  1465.0
 2025-12-24  2780.0  1250.0  218.0  308.0  3940.0  362.0  310.0  492.0  1455.0
 2025-12-29  2780.0  1250.0  238.0  322.0  3970.0  366.0  314.0  492.0  1530.0
 2025-12-30  2780.0  1260.0  234.0  322.0  4020.0  366.0  316.0  498.0  1600.0

              GTBO  ...    SHIP   FIRE   PSSI   DWGL   BOSS    INPS    SURE  \
 Date               ...
 2020-01-02  157.0  ...   760.0  246.0  179.0  342.0  171.0  4060.0  2950.0
 2020-01-03  160.0  ...   765.0  246.0  180.0  336.0  174.0  4000.0  2950.0
 2020-01-06  157.0  ...   760.0  232.0  178.0  324.0  193.0  4000.0  2940.0
 2020-01-07  147.0  ...   760.0  228.0  178.0  306.0  194.0  4100.0  2910.0
 2020-01-08  150.0  ...   755.0  284.0  177.0  294.0  183.0  4000.0  2900.0
 ...           ...  ...     ...    ...    ...    ...    ...     ...     ...
 2025-12-22  248.0  ...  4700.0  158.0  364.0  314.0   50.0   308.0  2610.0
 2025-12-23  244.0  ...  4630.0  155.0  350.0  318.0   50.0   338.0  2610.0
 2025-12-24  248.0  ...  4540.0  154.0  348.0  308.0   50.0   370.0  2650.0
 2025-12-29  244.0  ...  4500.0  167.0  368.0  320.0   50.0   370.0  2640.0
 2025-12-30  238.0  ...  4830.0  167.0  360.0  312.0   50.0   370.0  2670.0

              WOWS    TEBE    ADRO
 Date
 2020-01-02  230.0  1830.0  1495.0
 2020-01-03  220.0  1825.0  1465.0
 2020-01-06  224.0  1815.0  1465.0
 2020-01-07  214.0  1810.0  1540.0
 2020-01-08  210.0  1805.0  1505.0
 ...           ...     ...     ...
 2025-12-22   88.0  2290.0  1895.0
 2025-12-23   88.0  2290.0  1905.0
 2025-12-24   87.0  2410.0  1890.0
 2025-12-29   86.0  2470.0  1945.0
 2025-12-30   88.0  2610.0  1810.0

 [1447 rows x 43 columns],
 'industrial':               AMFG   APII   ARNA    ASGR    ASII  BHIT    HEXA   IBFN   IKBI  \
 Date
 2020-01-02  3540.0  168.0  440.0   945.0  6875.0  64.0  3480.0  242.0  260.0
 2020-01-03  3550.0  165.0  440.0   965.0  6950.0  63.0  3500.0  242.0  260.0
 2020-01-06  3600.0  179.0  436.0   945.0  6750.0  62.0  3420.0  296.0  260.0
 2020-01-07  3860.0  171.0  446.0   965.0  6775.0  62.0  3470.0  296.0  260.0
 2020-01-08  3620.0  171.0  436.0   945.0  6775.0  62.0  3380.0  310.0  262.0
 ...            ...    ...    ...     ...     ...   ...     ...    ...    ...
 2025-12-22  3250.0  208.0  535.0  1180.0  6575.0  40.0  4170.0  166.0  525.0
 2025-12-23  3270.0  202.0  525.0  1180.0  6500.0  39.0  4290.0  182.0  525.0
 2025-12-24  3300.0  202.0  525.0  1180.0  6625.0  39.0  4330.0  200.0  520.0
 2025-12-29  3390.0  204.0  525.0  1180.0  6675.0  39.0  4340.0  220.0  525.0
 2025-12-30  3390.0  206.0  530.0  1170.0  6700.0  39.0  4300.0  242.0  520.0

                    IMPC  ...   VOKS   MARK   SPTO   SKRN   CAKK    SOSS  \
 Date                     ...
 2020-01-02    95.000000  ...  312.0  452.0  835.0  106.0   69.0   402.0
 2020-01-03    95.000000  ...  322.0  458.0  830.0  110.0   68.0   416.0
 2020-01-06    94.545456  ...  324.0  452.0  820.0  109.0   68.0   416.0
 2020-01-07    94.545456  ...  322.0  456.0  815.0  108.0   65.0   392.0
 2020-01-08    94.545456  ...  302.0  452.0  815.0  107.0   65.0   408.0
 ...                 ...  ...    ...    ...    ...    ...    ...     ...
 2025-12-22  3630.000000  ...  258.0  825.0  640.0  555.0  177.0  1025.0
 2025-12-23  3940.000000  ...  254.0  810.0  645.0  560.0  182.0  1125.0
 2025-12-24  3840.000000  ...  250.0  820.0  650.0  560.0  180.0  1195.0
 2025-12-29  4020.000000  ...  250.0  825.0  645.0  560.0  177.0  1080.0
 2025-12-30  3930.000000  ...  254.0  825.0  650.0  545.0  180.0  1080.0

                   CCSI    BLUE    ARKA     SINI
 Date
 2020-01-02  215.000000   515.0  2070.0   1650.0
 2020-01-03  216.666672   510.0  2070.0   1650.0
 2020-01-06  218.333328   500.0  2120.0   1650.0
 2020-01-07  216.666672   510.0  2120.0   1650.0
 2020-01-08  213.333328   520.0  2120.0   1650.0
 ...                ...     ...     ...      ...
 2025-12-22  330.000000  3000.0    35.0  10750.0
 2025-12-23  332.000000  3000.0    36.0  11825.0
 2025-12-24  338.000000  2900.0    36.0  13000.0
 2025-12-29  358.000000  2890.0    35.0  14300.0
 2025-12-30  348.000000  2960.0    34.0  14500.0

 [1447 rows x 32 columns],
 'infrastruktur':                   ACST         ADHI    BALI    BUKK   CENT         CMNP  \
 Date
 2020-01-02  534.619690  1071.312866   900.0  1450.0   81.0  1659.880981
 2020-01-03  537.306274  1107.938965   880.0  1380.0   84.0  1673.303223
 2020-01-06  537.306274  1085.047607   870.0  1470.0   83.0  1673.303223
 2020-01-07  537.306274  1085.047607   935.0  1450.0   83.0  1789.629150
 2020-01-08  529.246643  1062.156250   900.0  1435.0   80.0  1789.629150
 ...                ...          ...     ...     ...    ...          ...
 2025-12-22  141.000000   250.000000  1715.0  1620.0  136.0  1305.000000
 2025-12-23  137.000000   250.000000  1745.0  1760.0  140.0  1315.000000
 2025-12-24  132.000000   260.000000  1590.0  1895.0  141.0  1400.000000
 2025-12-29  136.000000   272.000000  1630.0  1910.0  151.0  1580.000000
 2025-12-30  136.000000   268.000000  1780.0  1920.0  153.0  1765.000000

               EXCL   GOLD    ISAT   JKON  ...   MPOW   GMFI   PPRE   WEGE  \
 Date                                      ...
 2020-01-02  3210.0  228.0   717.5  505.0  ...  109.0  171.0  254.0  328.0
 2020-01-03  3200.0  224.0   722.5  505.0  ...  109.0  171.0  254.0  334.0
 2020-01-06  3240.0  226.0   712.5  505.0  ...  112.0  168.0  248.0  324.0
 2020-01-07  3250.0  226.0   725.0  505.0  ...  112.0  166.0  244.0  326.0
 2020-01-08  3300.0  226.0   712.5  505.0  ...  112.0  163.0  236.0  314.0
 ...            ...    ...     ...    ...  ...    ...    ...    ...    ...
 2025-12-22  3760.0  330.0  2440.0   86.0  ...  121.0   96.0  127.0   68.0
 2025-12-23  3740.0  322.0  2420.0   85.0  ...  122.0  105.0  127.0   66.0
 2025-12-24  3750.0  334.0  2400.0   85.0  ...  121.0   95.0  132.0   68.0
 2025-12-29  3830.0  332.0  2440.0   86.0  ...  123.0   91.0  138.0   68.0
 2025-12-30  3750.0  330.0  2320.0   86.0  ...  123.0   82.0  173.0   70.0

              IPCM    GHON    IPCC   MTPS    JAST    KEEN
 Date
 2020-01-02  185.0  1650.0   680.0  890.0  1415.0   555.0
 2020-01-03  184.0  1650.0   680.0  890.0  1395.0   550.0
 2020-01-06  181.0  1650.0   645.0  995.0  1395.0   545.0
 2020-01-07  183.0  1650.0   640.0  990.0  1460.0   510.0
 2020-01-08  181.0  1650.0   635.0  900.0  1660.0   496.0
 ...           ...     ...     ...    ...     ...     ...
 2025-12-22  366.0  1655.0  1405.0   81.0   102.0  1000.0
 2025-12-23  362.0  1660.0  1410.0   81.0   102.0  1020.0
 2025-12-24  356.0  1655.0  1410.0   81.0   102.0  1025.0
 2025-12-29  358.0  1675.0  1405.0   81.0   102.0  1025.0
 2025-12-30  358.0  1675.0  1385.0   81.0   102.0  1010.0

 [1447 rows x 37 columns],
 'kesehatan':               DVLA   INAF    KAEF    KLBF    MERK    MIKA   PYFA        SAME  \
 Date
 2020-01-02  2230.0  955.0  1250.0  1615.0  2900.0  2740.0  206.0  154.893188
 2020-01-03  2230.0  925.0  1215.0  1635.0  2870.0  2670.0  204.0  158.798065
 2020-01-06  2210.0  855.0  1170.0  1640.0  2900.0  2690.0  192.0  158.798065
 2020-01-07  2200.0  865.0  1160.0  1635.0  2830.0  2630.0  196.0  158.798065
 2020-01-08  2220.0  800.0  1120.0  1585.0  2830.0  2530.0  196.0  152.289948
 ...            ...    ...     ...     ...     ...     ...    ...         ...
 2025-12-22  1660.0  126.0   525.0  1225.0  3280.0  2440.0  500.0  364.000000
 2025-12-23  1660.0  126.0   520.0  1215.0  3290.0  2420.0  496.0  356.000000
 2025-12-24  1655.0  126.0   520.0  1210.0  3300.0  2450.0  480.0  358.000000
 2025-12-29  1655.0  126.0   520.0  1230.0  3360.0  2420.0  488.0  356.000000
 2025-12-30  1650.0  126.0   515.0  1205.0  3350.0  2380.0  476.0  362.000000

                   SIDO     SILO     SRAJ    TSPC    PRDA   PRIM    HEAL  \
 Date
 2020-01-02  635.151245   862.50    238.0  1360.0  3610.0  380.0   734.0
 2020-01-03  635.151245   843.75    246.0  1345.0  3700.0  380.0   734.0
 2020-01-06  640.113403   837.50    244.0  1370.0  3680.0  380.0   720.0
 2020-01-07  642.594421   843.75    244.0  1370.0  3680.0  400.0   714.0
 2020-01-08  645.075500   837.50    242.0  1360.0  3670.0  400.0   690.0
 ...                ...      ...      ...     ...     ...    ...     ...
 2025-12-22  545.000000  2570.00  16500.0  2760.0  2410.0   82.0  1400.0
 2025-12-23  545.000000  2510.00  16500.0  2760.0  2450.0   82.0  1385.0
 2025-12-24  540.000000  2510.00  16500.0  2760.0  2430.0   82.0  1375.0
 2025-12-29  535.000000  2500.00  16500.0  2770.0  2320.0   82.0  1375.0
 2025-12-30  540.000000  2740.00  16500.0  2850.0  2300.0   83.0  1375.0

               PEHA   IRRA
 Date
 2020-01-02  1085.0  645.0
 2020-01-03  1080.0  645.0
 2020-01-06  1085.0  670.0
 2020-01-07  1070.0  685.0
 2020-01-08  1050.0  665.0
 ...            ...    ...
 2025-12-22   300.0  434.0
 2025-12-23   296.0  428.0
 2025-12-24   298.0  414.0
 2025-12-29   290.0  418.0
 2025-12-30   300.0  424.0

 [1447 rows x 17 columns],
 'keuangan':              AMAG    APIC         ARTO   ASBI   ASDM        ASJT    ASMI  \
 Date
 2020-01-02  296.0   685.0   386.820343  304.0  547.5   92.625336  1240.0
 2020-01-03  296.0   700.0   386.820343  304.0  547.5   95.687332  1235.0
 2020-01-06  296.0   700.0   355.625153  304.0  547.5   98.749329  1230.0
 2020-01-07  296.0   700.0   355.625153  304.0  507.5   99.514824  1235.0
 2020-01-08  296.0   695.0   355.625153  304.0  507.5   99.514824  1240.0
 ...           ...     ...          ...    ...    ...         ...     ...
 2025-12-22  382.0  1600.0  1965.000000  468.0  580.0  145.000000    30.0
 2025-12-23  380.0  1595.0  1965.000000  466.0  590.0  156.000000    30.0
 2025-12-24  380.0  1535.0  1980.000000  426.0  580.0  172.000000    30.0
 2025-12-29  388.0  1600.0  1965.000000  440.0  595.0  194.000000    30.0
 2025-12-30  402.0  1460.0  1975.000000  450.0  595.0  190.000000    30.0

              BACA    BBCA         BBHI  ...    CASA         BRIS   JMAS  \
 Date                                    ...
 2020-01-02  300.0  6690.0    24.341820  ...   416.0   323.802521  880.0
 2020-01-03  304.0  6800.0    24.965969  ...   416.0   319.901306  880.0
 2020-01-06  308.0  6735.0    25.798168  ...   418.0   316.000061  875.0
 2020-01-07  308.0  6740.0    25.174019  ...   420.0   310.148193  855.0
 2020-01-08  308.0  6680.0    25.174019  ...   418.0   304.296356  850.0
 ...           ...     ...          ...  ...     ...          ...    ...
 2025-12-22  194.0  8175.0  1475.000000  ...  1600.0  2220.000000  182.0
 2025-12-23  182.0  8025.0  1465.000000  ...  1600.0  2240.000000  177.0
 2025-12-24  187.0  8025.0  1470.000000  ...  1600.0  2230.000000  192.0
 2025-12-29  252.0  8025.0  1440.000000  ...  1605.0  2260.000000  220.0
 2025-12-30  234.0  8075.0  1490.000000  ...  1610.0  2230.000000  210.0

               NICK    BTPS    TUGU    SFAN   FUJI        AGRO        AGRS
 Date
 2020-01-02   316.0  4160.0  1725.0  1055.0  113.0  192.743835  105.119186
 2020-01-03   316.0  4100.0  1700.0  1030.0  114.0  194.700623  102.316010
 2020-01-06   312.0  3990.0  1710.0  1025.0  113.0  191.765442   98.111244
 2020-01-07   312.0  4190.0  1725.0  1025.0  112.0  194.700623   98.812035
 2020-01-08   310.0  4170.0  1725.0  1025.0  106.0  187.851852  110.725548
 ...            ...     ...     ...     ...    ...         ...         ...
 2025-12-22  1355.0  1205.0  1110.0  1940.0  700.0  228.000000   79.000000
 2025-12-23  1235.0  1190.0  1130.0  1935.0  695.0  228.000000   79.000000
 2025-12-24  1235.0  1250.0  1115.0  1935.0  695.0  228.000000   78.000000
 2025-12-29  1200.0  1200.0  1180.0  1940.0  690.0  228.000000   80.000000
 2025-12-30  1220.0  1205.0  1165.0  1940.0  695.0  230.000000   81.000000

 [1447 rows x 68 columns],
 'properti':              APLN   ASRI  BAPA   BEST    BSDE    CTRA   DILD   DMAS   INPP  \
 Date

## Pearson

In [59]:
import pandas as pd
from itertools import combinations

pearson_results = {}

for sektor, df_sektor in cleaned_df.items():

    # Filter hanya pakai data 2020-01-01 sampai 2023-12-31
    df_train = df_sektor.loc["2020-01-01":"2023-12-31"]

    # hitung matriks korelasi
    corr_matrix = df_train.corr(method="pearson")

    pairs = []

    # ambil hanya kombinasi unik (tanpa duplikasi & diagonal)
    for saham1, saham2 in combinations(corr_matrix.columns, 2):
        corr_value = corr_matrix.loc[saham1, saham2]
        pairs.append((saham1, saham2, corr_value))

    # ubah jadi DataFrame
    pair_df = pd.DataFrame(pairs, columns=["Saham_1", "Saham_2", "Correlation"])

    # urutkan dari tertinggi
    pair_df = pair_df.sort_values(by="Correlation", ascending=False)

    pearson_results[sektor] = pair_df

    print(sektor, "→ total pair:", len(pair_df))

barang_baku → total pair: 2145
barang_konsumsi_non_primer → total pair: 1953
barang_konsumsi_primer → total pair: 1891
energi → total pair: 903
industrial → total pair: 496
infrastruktur → total pair: 666
kesehatan → total pair: 136
keuangan → total pair: 2278
properti → total pair: 435
teknologi → total pair: 105
transportasi_dan_logistik → total pair: 105

In [61]:
for sektor, df_sektor in cleaned_df.items():

    df_train = df_sektor.loc["2020-01-01":"2023-12-31"]
    corr_matrix = df_train.corr(method="pearson")

    pairs = []

    for saham1, saham2 in combinations(corr_matrix.columns, 2):
        corr_value = corr_matrix.loc[saham1, saham2]
        pairs.append((saham1, saham2, corr_value))

    pair_df = pd.DataFrame(pairs, columns=["Saham_1", "Saham_2", "Correlation"])
    pair_df = pair_df.sort_values(by="Correlation", ascending=False)

    pearson_results[sektor] = pair_df

    # ── PRINT TOP 5 PER SEKTOR ────────────────────────────────
    print(f"\n{'='*50}")
    print(f"  SEKTOR: {sektor}  |  Top 5 dari {len(pair_df)} pair")
    print(f"{'='*50}")
    print(f"{'No.':<5} {'Saham 1':<12} {'Saham 2':<12} {'Korelasi':>10}")
    print(f"{'-'*5} {'-'*12} {'-'*12} {'-'*10}")
    for i, row in enumerate(pair_df.head(5).itertuples(), start=1):
        print(f"{i:<5} {row.Saham_1:<12} {row.Saham_2:<12} {row.Correlation:>10.4f}")

==================================================
  SEKTOR: barang_baku  |  Top 5 dari 2145 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     SPMA         UNIC             0.9481
2     ANTM         IPOL             0.9355
3     IPOL         PBID             0.9326
4     ZINC         HKMU             0.9263
5     NIKL         SMBR             0.9260

==================================================
  SEKTOR: barang_konsumsi_non_primer  |  Top 5 dari 1953 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     MAPI         PANR             0.9604
2     AUTO         MAPA             0.9511
3     MAPI         MAPA             0.9324
4     AUTO         SMSM             0.9316
5     AUTO         MAPI             0.9216

==================================================
  SEKTOR: barang_konsumsi_primer  |  Top 5 dari 1891 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     ADES         AMRT             0.9527
2     DLTA         MLBI             0.9354
3     GGRM         HMSP             0.9269
4     ADES         MIDI             0.9203
5     HMSP         UNVR             0.9186

==================================================
  SEKTOR: energi  |  Top 5 dari 903 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     ITMG         ADRO             0.9653
2     ITMG         MBAP             0.9644
3     MBAP         ADRO             0.9426
4     BSSR         ADRO             0.9392
5     MBSS         PSSI             0.9367

==================================================
  SEKTOR: industrial  |  Top 5 dari 496 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     HEXA         IMPC             0.9404
2     IMPC         MLIA             0.9364
3     MLIA         CCSI             0.9308
4     AMFG         IMPC             0.9260
5     AMFG         MLIA             0.9192

==================================================
  SEKTOR: infrastruktur  |  Top 5 dari 666 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     WIKA         WEGE             0.9596
2     ADHI         PTPP             0.9582
3     PTPP         WIKA             0.9273
4     PPRE         WEGE             0.8989
5     WIKA         PPRE             0.8923

==================================================
  SEKTOR: kesehatan  |  Top 5 dari 136 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     INAF         KAEF             0.9932
2     INAF         PEHA             0.9218
3     KAEF         PEHA             0.9126
4     MERK         HEAL             0.8894
5     KLBF         MERK             0.8323

==================================================
  SEKTOR: keuangan  |  Top 5 dari 2278 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     PNBN         PNLF             0.9689
2     BBCA         BMRI             0.9534
3     BBNI         BMRI             0.9506
4     BBCA         BBNI             0.9481
5     PALM         SRTG             0.9460

==================================================
  SEKTOR: properti  |  Top 5 dari 435 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     POLL         URBN             0.9106
2     RDTX         PANI             0.9006
3     ASRI         BSDE             0.8737
4     BSDE         CTRA             0.8592
5     APLN         ASRI             0.8469

==================================================
  SEKTOR: teknologi  |  Top 5 dari 105 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     MLPT         DMMX             0.8880
2     MTDL         MCAS             0.8875
3     MLPT         MCAS             0.8534
4     MCAS         NFCX             0.8528
5     KIOS         DIVA             0.8065

==================================================
  SEKTOR: transportasi_dan_logistik  |  Top 5 dari 105 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     SMDR         TMAS             0.9014
2     BPTR         JAYA             0.7673
3     ASSA         TNCA             0.7667
4     TNCA         BPTR             0.7532
5     ASSA         IMJS             0.7284

## Spearman

In [62]:
import pandas as pd
from itertools import combinations

spearman_results = {}

for sektor, df_sektor in cleaned_df.items():

    df_train = df_sektor.loc["2020-01-01":"2023-12-31"]
    corr_matrix = df_train.corr(method="spearman")

    pairs = []

    for saham1, saham2 in combinations(corr_matrix.columns, 2):
        corr_value = corr_matrix.loc[saham1, saham2]
        pairs.append((saham1, saham2, corr_value))

    pair_df = pd.DataFrame(pairs, columns=["Saham_1", "Saham_2", "Correlation"])
    pair_df = pair_df.sort_values(by="Correlation", ascending=False)

    spearman_results[sektor] = pair_df

In [64]:
# Output top 5
for sektor, pair_df in spearman_results.items():
    print(f"\n{'='*50}")
    print(f"  SEKTOR: {sektor}  |  Top 5 dari {len(pair_df)} pair")
    print(f"{'='*50}")
    print(f"{'No.':<5} {'Saham 1':<12} {'Saham 2':<12} {'Korelasi':>10}")
    print(f"{'-'*5} {'-'*12} {'-'*12} {'-'*10}")
    for i, row in enumerate(pair_df.head(10).itertuples(), start=1):
        print(f"{i:<5} {row.Saham_1:<12} {row.Saham_2:<12} {row.Correlation:>10.4f}")

==================================================
  SEKTOR: barang_baku  |  Top 5 dari 2145 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     NIKL         SMBR             0.9550
2     BMSR         LTLS             0.9503
3     KRAS         NIKL             0.9470
4     KRAS         SMBR             0.9402
5     SPMA         UNIC             0.9387
6     AKPI         BMSR             0.9358
7     AKPI         TRST             0.9221
8     UNIC         SMKL             0.9213
9     AKPI         LTLS             0.9188
10    ESSA         LTLS             0.9170

==================================================
  SEKTOR: barang_konsumsi_non_primer  |  Top 5 dari 1953 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     MAPI         MAPA             0.9310
2     PANR         EAST             0.9304
3     MAPI         PANR             0.9151
4     AUTO         EAST             0.9130
5     AUTO         MAPI             0.9078
6     AUTO         PANR             0.9022
7     PANR         MAPA             0.8948
8     PJAA         MAPA             0.8909
9     MAPI         EAST             0.8873
10    MICE         EAST             0.8752

==================================================
  SEKTOR: barang_konsumsi_primer  |  Top 5 dari 1891 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     HERO         RANC             0.9423
2     ADES         MIDI             0.9416
3     ADES         AMRT             0.9282
4     ADES         BUDI             0.9244
5     AMRT         MIDI             0.9114
6     ALTO         GGRM             0.8946
7     AMRT         MRAT             0.8903
8     ALTO         AGAR             0.8897
9     GGRM         HMSP             0.8865
10    GGRM         AGAR             0.8847

==================================================
  SEKTOR: energi  |  Top 5 dari 903 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     ITMG         MBAP             0.9774
2     ITMG         ADRO             0.9688
3     MBAP         ADRO             0.9491
4     INDY         ITMG             0.9430
5     INDY         ADRO             0.9424
6     AKRA         WINS             0.9420
7     ENRG         MBAP             0.9409
8     INDY         PTBA             0.9374
9     ENRG         ITMG             0.9344
10    MBAP         PSSI             0.9342

==================================================
  SEKTOR: industrial  |  Top 5 dari 496 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     KOBX         MLIA             0.9317
2     ARNA         KOBX             0.9299
3     IBFN         INTA             0.9131
4     HEXA         IMPC             0.9122
5     KOBX         CCSI             0.9097
6     ARNA         MLIA             0.9034
7     IMPC         SKRN             0.9010
8     AMFG         IMPC             0.8911
9     AMFG         MLIA             0.8907
10    AMFG         HEXA             0.8906

==================================================
  SEKTOR: infrastruktur  |  Top 5 dari 666 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     WIKA         WEGE             0.9543
2     ADHI         PTPP             0.9496
3     PTPP         WEGE             0.9429
4     PPRE         WEGE             0.9255
5     PTPP         WIKA             0.9063
6     WIKA         PPRE             0.9059
7     ADHI         WEGE             0.9037
8     TBIG         GHON             0.8941
9     PTPP         PPRE             0.8902
10    ADHI         PPRE             0.8608

==================================================
  SEKTOR: kesehatan  |  Top 5 dari 136 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     INAF         KAEF             0.9754
2     INAF         PEHA             0.9333
3     KAEF         PEHA             0.9117
4     MERK         HEAL             0.8774
5     KLBF         MERK             0.8468
6     SILO         SRAJ             0.8069
7     SILO         HEAL             0.7725
8     PYFA         IRRA             0.7530
9     SAME         PRDA             0.7496
10    KLBF         HEAL             0.7386

==================================================
  SEKTOR: keuangan  |  Top 5 dari 2278 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     BBNI         BMRI             0.9755
2     BBCA         BBRI             0.9649
3     BBCA         BMRI             0.9584
4     BBRI         BMRI             0.9558
5     PNBN         PNLF             0.9546
6     BBNI         BBRI             0.9431
7     BBCA         BBNI             0.9429
8     ARTO         AGRO             0.9420
9     BBHI         SRTG             0.9418
10    YULE         SFAN             0.9376

==================================================
  SEKTOR: properti  |  Top 5 dari 435 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     POLL         URBN             0.9277
2     RDTX         PANI             0.9238
3     PUDP         PANI             0.8936
4     SMDM         PANI             0.8543
5     ASRI         BSDE             0.8510
6     LPKR         POLL             0.8450
7     PUDP         RDTX             0.8440
8     BSDE         JRPT             0.8197
9     BSDE         CTRA             0.8183
10    BAPA         SMDM             0.8073

==================================================
  SEKTOR: teknologi  |  Top 5 dari 105 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     MLPT         DMMX             0.9550
2     MCAS         DMMX             0.9071
3     KREN         HDIT             0.9032
4     MLPT         MCAS             0.8909
5     MTDL         MCAS             0.8869
6     ATIC         HDIT             0.8596
7     ATIC         KREN             0.8501
8     MTDL         DMMX             0.8337
9     MCAS         NFCX             0.8331
10    NFCX         DMMX             0.8238

==================================================
  SEKTOR: transportasi_dan_logistik  |  Top 5 dari 105 pair
==================================================
No.   Saham 1      Saham 2        Korelasi
----- ------------ ------------ ----------
1     SMDR         TMAS             0.9252
2     NELY         TMAS             0.8263
3     ASSA         TNCA             0.8215
4     NELY         SMDR             0.7875
5     TMAS         BPTR             0.7742
6     ASSA         IMJS             0.7536
7     SMDR         BPTR             0.7513
8     NELY         JAYA             0.7449
9     NELY         BPTR             0.7030
10    TMAS         JAYA             0.7015

## Cointegration

In [65]:
import pandas as pd
from itertools import combinations
from statsmodels.tsa.stattools import coint

cointegration_results = {}
top5_per_sektor = {}

for sektor, df_sektor in cleaned_df.items():
    print(f"\n=== Sektor: {sektor} (Two-Way Screening) ===")

    # Filter data training
    df_train = df_sektor.loc["2020-01-01":"2023-12-31"]

    pairs = []
    unique_combinations = list(combinations(df_train.columns, 2))
    total_pairs = len(unique_combinations)
    counter = 0

    for saham1, saham2 in unique_combinations:
        counter += 1
        series1 = df_train[saham1]
        series2 = df_train[saham2]

        score12, pval12, _ = coint(series1, series2)
        score21, pval21, _ = coint(series2, series1)

        if pval12 < pval21:
            best_y, best_x, best_score, best_pval = saham1, saham2, score12, pval12
        else:
            best_y, best_x, best_score, best_pval = saham2, saham1, score21, pval21

        print(f"[{counter}/{total_pairs}] Best orientation: {best_y}-{best_x} | p-value: {best_pval:.12e}")

        pairs.append((best_y, best_x, best_score, best_pval))

    pair_df = pd.DataFrame(pairs, columns=["Saham_Y", "Saham_X", "Test_Statistic", "P_Value"])
    pair_df = pair_df.sort_values(by="P_Value").reset_index(drop=True)
    cointegration_results[sektor] = pair_df

    significant = pair_df[pair_df["P_Value"] < 0.05]
    top5 = significant.head(5).reset_index(drop=True)
    top5_per_sektor[sektor] = top5

    print(f"\n  → Top 5 cointegrated pairs ({sektor}):")
    if top5.empty:
        print("    Tidak ada pair cointegrated (p < 0.05)")
    else:
        print(top5[["Saham_Y", "Saham_X", "P_Value"]].to_string())

=== Sektor: barang_baku (Two-Way Screening) ===
[1/2145] Best orientation: ALDO-AKPI | p-value: 5.491204538583e-01
[2/2145] Best orientation: ALKA-AKPI | p-value: 3.470318401322e-01
[3/2145] Best orientation: ALMI-AKPI | p-value: 2.540166526892e-03
[4/2145] Best orientation: ANTM-AKPI | p-value: 5.098038327683e-01
[5/2145] Best orientation: AKPI-APLI | p-value: 8.271089774226e-01
[6/2145] Best orientation: BAJA-AKPI | p-value: 7.282063125777e-01
[7/2145] Best orientation: BMSR-AKPI | p-value: 2.387529132094e-03
[8/2145] Best orientation: BRPT-AKPI | p-value: 8.373367337870e-04
[9/2145] Best orientation: AKPI-BTON | p-value: 6.610611287851e-01
[10/2145] Best orientation: CITA-AKPI | p-value: 2.486364847199e-01
[11/2145] Best orientation: AKPI-CLPI | p-value: 3.362550708017e-01
[12/2145] Best orientation: DKFT-AKPI | p-value: 2.691328494839e-01
[13/2145] Best orientation: EKAD-AKPI | p-value: 3.786147630153e-01
[14/2145] Best orientation: ESSA-AKPI | p-value: 6.432478402938e-05
[15/2145] Best orientation: ETWA-AKPI | p-value: 3.638150826026e-01
[16/2145] Best orientation: FPNI-AKPI | p-value: 2.124565227465e-01
[17/2145] Best orientation: GDST-AKPI | p-value: 2.107744354763e-01
[18/2145] Best orientation: AKPI-IGAR | p-value: 7.149732173810e-02
[19/2145] Best orientation: AKPI-INAI | p-value: 7.601778698836e-01
[20/2145] Best orientation: INCI-AKPI | p-value: 5.665368696478e-01
[21/2145] Best orientation: INCO-AKPI | p-value: 4.539044946578e-02
[22/2145] Best orientation: INKP-AKPI | p-value: 1.938191184496e-01
[23/2145] Best orientation: INTD-AKPI | p-value: 2.126021044588e-01
[24/2145] Best orientation: INTP-AKPI | p-value: 3.600449408820e-03
[25/2145] Best orientation: IPOL-AKPI | p-value: 5.888151135527e-01
[26/2145] Best orientation: ISSP-AKPI | p-value: 5.545578548813e-01
[27/2145] Best orientation: AKPI-KDSI | p-value: 7.799978927392e-01
[28/2145] Best orientation: AKPI-KRAS | p-value: 7.698154209566e-01
[29/2145] Best orientation: LMSH-AKPI | p-value: 4.761007978846e-02
[30/2145] Best orientation: AKPI-LTLS | p-value: 3.598513043524e-01
[31/2145] Best orientation: MDKA-AKPI | p-value: 4.109197508292e-02
[32/2145] Best orientation: NIKL-AKPI | p-value: 5.573745911188e-01
[33/2145] Best orientation: OKAS-AKPI | p-value: 1.856512876267e-02
[34/2145] Best orientation: PICO-AKPI | p-value: 3.806782021725e-04
[35/2145] Best orientation: PSAB-AKPI | p-value: 5.393061993893e-02
[36/2145] Best orientation: SMBR-AKPI | p-value: 5.729055360352e-01
[37/2145] Best orientation: SMCB-AKPI | p-value: 5.743271109520e-01
[38/2145] Best orientation: SMGR-AKPI | p-value: 8.201897783811e-02
[39/2145] Best orientation: AKPI-SPMA | p-value: 1.589101828616e-01
[40/2145] Best orientation: AKPI-SQMI | p-value: 4.423033873896e-01
[41/2145] Best orientation: SRSN-AKPI | p-value: 7.626380329034e-03
[42/2145] Best orientation: AKPI-TBMS | p-value: 8.950407106429e-01
[43/2145] Best orientation: TINS-AKPI | p-value: 7.307158147993e-01
[44/2145] Best orientation: TKIM-AKPI | p-value: 8.635729320216e-02
[45/2145] Best orientation: AKPI-TPIA | p-value: 8.462208750330e-01
[46/2145] Best orientation: AKPI-TRST | p-value: 1.217867860686e-02
[47/2145] Best orientation: AKPI-UNIC | p-value: 3.397149702116e-01
[48/2145] Best orientation: WTON-AKPI | p-value: 2.898118363902e-01
[49/2145] Best orientation: YPAS-AKPI | p-value: 3.726284653704e-06
[50/2145] Best orientation: KMTR-AKPI | p-value: 4.708893465391e-01
[51/2145] Best orientation: MDKI-AKPI | p-value: 2.584470231518e-01
[52/2145] Best orientation: ZINC-AKPI | p-value: 7.977965735499e-03
[53/2145] Best orientation: PBID-AKPI | p-value: 5.953556720895e-01
[54/2145] Best orientation: TDPM-AKPI | p-value: 6.379505942308e-05
[55/2145] Best orientation: AKPI-MOLI | p-value: 1.632127980855e-01
[56/2145] Best orientation: HKMU-AKPI | p-value: 5.951333055946e-08
[57/2145] Best orientation: KAYU-AKPI | p-value: 7.265798689482e-01
[58/2145] Best orientation: SMKL-AKPI | p-value: 1.960953351146e-01
[59/2145] Best orientation: GGRP-AKPI | p-value: 3.468709639855e-01
[60/2145] Best orientation: OPMS-AKPI | p-value: 3.353303964992e-01
[61/2145] Best orientation: PURE-AKPI | p-value: 2.324324725719e-01
[62/2145] Best orientation: IFSH-AKPI | p-value: 5.467547029146e-01
[63/2145] Best orientation: IFII-AKPI | p-value: 1.247453285500e-06
[64/2145] Best orientation: ADMG-AKPI | p-value: 4.498133965251e-01
[65/2145] Best orientation: AGII-AKPI | p-value: 1.162053067816e-02
[66/2145] Best orientation: ALKA-ALDO | p-value: 3.489278247088e-01
[67/2145] Best orientation: ALMI-ALDO | p-value: 1.227904535340e-01
[68/2145] Best orientation: ANTM-ALDO | p-value: 2.381201924149e-01
[69/2145] Best orientation: ALDO-APLI | p-value: 6.308006900975e-01
[70/2145] Best orientation: ALDO-BAJA | p-value: 3.755693475894e-01
[71/2145] Best orientation: BMSR-ALDO | p-value: 4.248830146388e-01
[72/2145] Best orientation: BRPT-ALDO | p-value: 6.542616060808e-03
[73/2145] Best orientation: ALDO-BTON | p-value: 1.645219715539e-01
[74/2145] Best orientation: CITA-ALDO | p-value: 5.435497532744e-01
[75/2145] Best orientation: ALDO-CLPI | p-value: 6.833488178861e-02
[76/2145] Best orientation: DKFT-ALDO | p-value: 3.074846528013e-01
[77/2145] Best orientation: ALDO-EKAD | p-value: 2.804542127229e-01
[78/2145] Best orientation: ALDO-ESSA | p-value: 2.930951361130e-01
[79/2145] Best orientation: ETWA-ALDO | p-value: 5.841746798283e-01
[80/2145] Best orientation: FPNI-ALDO | p-value: 2.294758790579e-01
[81/2145] Best orientation: GDST-ALDO | p-value: 4.196567190305e-01
[82/2145] Best orientation: ALDO-IGAR | p-value: 1.348340964820e-01
[83/2145] Best orientation: INAI-ALDO | p-value: 6.324575941625e-01
[84/2145] Best orientation: INCI-ALDO | p-value: 5.663314931767e-01
[85/2145] Best orientation: ALDO-INCO | p-value: 4.982204076548e-01
[86/2145] Best orientation: INKP-ALDO | p-value: 1.900071830962e-01
[87/2145] Best orientation: INTD-ALDO | p-value: 1.229729799244e-01
[88/2145] Best orientation: INTP-ALDO | p-value: 8.928422829532e-03
[89/2145] Best orientation: IPOL-ALDO | p-value: 3.196330572274e-01
[90/2145] Best orientation: ALDO-ISSP | p-value: 3.529283069708e-03
[91/2145] Best orientation: ALDO-KDSI | p-value: 4.321398605159e-01
[92/2145] Best orientation: ALDO-KRAS | p-value: 7.170183469589e-01
[93/2145] Best orientation: LMSH-ALDO | p-value: 5.121157917554e-03
[94/2145] Best orientation: ALDO-LTLS | p-value: 5.576466085200e-01
[95/2145] Best orientation: ALDO-MDKA | p-value: 1.487619015581e-01
[96/2145] Best orientation: NIKL-ALDO | p-value: 5.945269940129e-01
[97/2145] Best orientation: OKAS-ALDO | p-value: 3.685062907160e-02
[98/2145] Best orientation: PICO-ALDO | p-value: 1.207907077488e-04
[99/2145] Best orientation: PSAB-ALDO | p-value: 1.756146624300e-01
[100/2145] Best orientation: SMBR-ALDO | p-value: 6.652075822704e-01
[101/2145] Best orientation: ALDO-SMCB | p-value: 2.454565018541e-01
[102/2145] Best orientation: SMGR-ALDO | p-value: 1.080860112979e-01
[103/2145] Best orientation: ALDO-SPMA | p-value: 1.198216582366e-01
[104/2145] Best orientation: ALDO-SQMI | p-value: 3.834500470436e-01
[105/2145] Best orientation: SRSN-ALDO | p-value: 4.960640676810e-02
[106/2145] Best orientation: ALDO-TBMS | p-value: 2.553802899475e-01
[107/2145] Best orientation: ALDO-TINS | p-value: 6.103685948631e-01
[108/2145] Best orientation: TKIM-ALDO | p-value: 9.374321152584e-02
[109/2145] Best orientation: ALDO-TPIA | p-value: 5.604051999532e-01
[110/2145] Best orientation: ALDO-TRST | p-value: 4.807927076615e-01
[111/2145] Best orientation: ALDO-UNIC | p-value: 1.358050253212e-01
[112/2145] Best orientation: WTON-ALDO | p-value: 3.064926972498e-01
[113/2145] Best orientation: YPAS-ALDO | p-value: 1.540908629612e-04
[114/2145] Best orientation: KMTR-ALDO | p-value: 5.699950697877e-01
[115/2145] Best orientation: MDKI-ALDO | p-value: 1.448837914111e-01
[116/2145] Best orientation: ZINC-ALDO | p-value: 2.694423991710e-02
[117/2145] Best orientation: PBID-ALDO | p-value: 4.146142473773e-01
[118/2145] Best orientation: TDPM-ALDO | p-value: 9.036116928522e-05
[119/2145] Best orientation: ALDO-MOLI | p-value: 5.857580088659e-01
[120/2145] Best orientation: HKMU-ALDO | p-value: 4.720005388219e-08
[121/2145] Best orientation: ALDO-KAYU | p-value: 6.933502037380e-01
[122/2145] Best orientation: SMKL-ALDO | p-value: 7.273298899545e-02
[123/2145] Best orientation: GGRP-ALDO | p-value: 1.127346548804e-02
[124/2145] Best orientation: OPMS-ALDO | p-value: 3.235282857674e-01
[125/2145] Best orientation: PURE-ALDO | p-value: 1.628062875382e-01
[126/2145] Best orientation: ALDO-IFSH | p-value: 1.094949682641e-01
[127/2145] Best orientation: IFII-ALDO | p-value: 1.959001306579e-05
[128/2145] Best orientation: ADMG-ALDO | p-value: 1.502309046854e-01
[129/2145] Best orientation: ALDO-AGII | p-value: 2.571768406460e-01
[130/2145] Best orientation: ALMI-ALKA | p-value: 2.695103775973e-02
[131/2145] Best orientation: ALKA-ANTM | p-value: 3.079266044997e-01
[132/2145] Best orientation: ALKA-APLI | p-value: 3.939877790833e-02
[133/2145] Best orientation: ALKA-BAJA | p-value: 2.338319339530e-01
[134/2145] Best orientation: ALKA-BMSR | p-value: 3.412539711392e-01
[135/2145] Best orientation: BRPT-ALKA | p-value: 3.169012862353e-03
[136/2145] Best orientation: ALKA-BTON | p-value: 3.282148428935e-01
[137/2145] Best orientation: ALKA-CITA | p-value: 2.602306361433e-01
[138/2145] Best orientation: ALKA-CLPI | p-value: 3.399226511742e-01
[139/2145] Best orientation: DKFT-ALKA | p-value: 3.940001372104e-02
[140/2145] Best orientation: ALKA-EKAD | p-value: 3.054986861410e-01
[141/2145] Best orientation: ALKA-ESSA | p-value: 3.322012944166e-01
[142/2145] Best orientation: ALKA-ETWA | p-value: 2.696328784253e-01
[143/2145] Best orientation: ALKA-FPNI | p-value: 2.792715182527e-01
[144/2145] Best orientation: ALKA-GDST | p-value: 3.032490695707e-01
[145/2145] Best orientation: ALKA-IGAR | p-value: 4.127100927602e-01
[146/2145] Best orientation: ALKA-INAI | p-value: 3.012875115733e-02
[147/2145] Best orientation: ALKA-INCI | p-value: 1.684491827772e-01
[148/2145] Best orientation: ALKA-INCO | p-value: 4.413318044197e-01
[149/2145] Best orientation: INKP-ALKA | p-value: 1.842015580375e-01
[150/2145] Best orientation: INTD-ALKA | p-value: 3.107061627113e-01
[151/2145] Best orientation: INTP-ALKA | p-value: 6.789307013584e-03
[152/2145] Best orientation: ALKA-IPOL | p-value: 3.408059893281e-01
[153/2145] Best orientation: ALKA-ISSP | p-value: 3.480455168828e-01
[154/2145] Best orientation: ALKA-KDSI | p-value: 5.569135529741e-02
[155/2145] Best orientation: ALKA-KRAS | p-value: 2.488627649505e-02
[156/2145] Best orientation: LMSH-ALKA | p-value: 2.337493790130e-01
[157/2145] Best orientation: ALKA-LTLS | p-value: 2.582142416544e-01
[158/2145] Best orientation: ALKA-MDKA | p-value: 3.476691041255e-01
[159/2145] Best orientation: ALKA-NIKL | p-value: 1.774932786249e-02
[160/2145] Best orientation: OKAS-ALKA | p-value: 2.677176070448e-02
[161/2145] Best orientation: PICO-ALKA | p-value: 4.478858987402e-05
[162/2145] Best orientation: PSAB-ALKA | p-value: 2.379948761359e-02
[163/2145] Best orientation: ALKA-SMBR | p-value: 8.035736257956e-02
[164/2145] Best orientation: ALKA-SMCB | p-value: 3.997490552692e-01
[165/2145] Best orientation: SMGR-ALKA | p-value: 1.147802752440e-01
[166/2145] Best orientation: ALKA-SPMA | p-value: 3.488997594211e-01
[167/2145] Best orientation: ALKA-SQMI | p-value: 1.965258415213e-01
[168/2145] Best orientation: SRSN-ALKA | p-value: 4.548481950192e-02
[169/2145] Best orientation: ALKA-TBMS | p-value: 3.239267216007e-01
[170/2145] Best orientation: ALKA-TINS | p-value: 9.537854637618e-02
[171/2145] Best orientation: TKIM-ALKA | p-value: 5.933005817084e-02
[172/2145] Best orientation: ALKA-TPIA | p-value: 2.429519565563e-01
[173/2145] Best orientation: ALKA-TRST | p-value: 3.426578716994e-01
[174/2145] Best orientation: ALKA-UNIC | p-value: 3.484353312603e-01
[175/2145] Best orientation: WTON-ALKA | p-value: 3.367576554540e-02
[176/2145] Best orientation: YPAS-ALKA | p-value: 1.043061578086e-02
[177/2145] Best orientation: ALKA-KMTR | p-value: 1.101565946749e-01
[178/2145] Best orientation: MDKI-ALKA | p-value: 2.565687133392e-01
[179/2145] Best orientation: ZINC-ALKA | p-value: 2.528365567681e-03
[180/2145] Best orientation: ALKA-PBID | p-value: 3.077120868534e-01
[181/2145] Best orientation: TDPM-ALKA | p-value: 3.402449188467e-05
[182/2145] Best orientation: ALKA-MOLI | p-value: 2.870073546782e-01
[183/2145] Best orientation: HKMU-ALKA | p-value: 8.185507880032e-09
[184/2145] Best orientation: KAYU-ALKA | p-value: 3.426062157914e-03
[185/2145] Best orientation: ALKA-SMKL | p-value: 4.362324527332e-01
[186/2145] Best orientation: ALKA-GGRP | p-value: 3.459118653828e-01
[187/2145] Best orientation: ALKA-OPMS | p-value: 1.520753621902e-01
[188/2145] Best orientation: ALKA-PURE | p-value: 1.892593166590e-01
[189/2145] Best orientation: ALKA-IFSH | p-value: 4.333616160401e-01
[190/2145] Best orientation: IFII-ALKA | p-value: 1.340392951429e-02
[191/2145] Best orientation: ALKA-ADMG | p-value: 1.545696450180e-01
[192/2145] Best orientation: ALKA-AGII | p-value: 3.280599895460e-01
[193/2145] Best orientation: ALMI-ANTM | p-value: 1.385409213219e-01
[194/2145] Best orientation: ALMI-APLI | p-value: 1.116058935516e-01
[195/2145] Best orientation: ALMI-BAJA | p-value: 7.305096195203e-02
[196/2145] Best orientation: ALMI-BMSR | p-value: 3.899056235870e-02
[197/2145] Best orientation: BRPT-ALMI | p-value: 3.349362293609e-03
[198/2145] Best orientation: ALMI-BTON | p-value: 7.467001186193e-02
[199/2145] Best orientation: ALMI-CITA | p-value: 3.690959639639e-02
[200/2145] Best orientation: ALMI-CLPI | p-value: 1.408279144022e-01
[201/2145] Best orientation: ALMI-DKFT | p-value: 2.010387767730e-01
[202/2145] Best orientation: ALMI-EKAD | p-value: 9.377106814379e-02
[203/2145] Best orientation: ALMI-ESSA | p-value: 3.406148787327e-02
[204/2145] Best orientation: ALMI-ETWA | p-value: 1.556442916483e-01
[205/2145] Best orientation: ALMI-FPNI | p-value: 4.416189600892e-02
[206/2145] Best orientation: ALMI-GDST | p-value: 1.177191795928e-01
[207/2145] Best orientation: ALMI-IGAR | p-value: 7.599177844382e-02
[208/2145] Best orientation: ALMI-INAI | p-value: 1.729498631778e-01
[209/2145] Best orientation: ALMI-INCI | p-value: 8.917483247461e-02
[210/2145] Best orientation: ALMI-INCO | p-value: 8.277495004653e-02
[211/2145] Best orientation: ALMI-INKP | p-value: 1.015592269626e-01
[212/2145] Best orientation: ALMI-INTD | p-value: 6.275300396975e-02
[213/2145] Best orientation: INTP-ALMI | p-value: 1.348316297208e-02
[214/2145] Best orientation: ALMI-IPOL | p-value: 1.203376641256e-01
[215/2145] Best orientation: ALMI-ISSP | p-value: 1.057671647550e-01
[216/2145] Best orientation: ALMI-KDSI | p-value: 8.308220091100e-02
[217/2145] Best orientation: ALMI-KRAS | p-value: 1.246686967488e-01
[218/2145] Best orientation: LMSH-ALMI | p-value: 1.684055088669e-02
[219/2145] Best orientation: ALMI-LTLS | p-value: 1.454289335052e-01
[220/2145] Best orientation: ALMI-MDKA | p-value: 4.028118980415e-02
[221/2145] Best orientation: ALMI-NIKL | p-value: 1.225186487525e-01
[222/2145] Best orientation: OKAS-ALMI | p-value: 3.310159163314e-02
[223/2145] Best orientation: PICO-ALMI | p-value: 7.542518642773e-08
[224/2145] Best orientation: ALMI-PSAB | p-value: 8.256333253043e-02
[225/2145] Best orientation: ALMI-SMBR | p-value: 1.609328317812e-01
[226/2145] Best orientation: ALMI-SMCB | p-value: 1.420868537921e-01
[227/2145] Best orientation: ALMI-SMGR | p-value: 8.154126334914e-02
[228/2145] Best orientation: ALMI-SPMA | p-value: 5.924259915090e-02
[229/2145] Best orientation: ALMI-SQMI | p-value: 6.659399428768e-02
[230/2145] Best orientation: SRSN-ALMI | p-value: 1.746785372903e-02
[231/2145] Best orientation: ALMI-TBMS | p-value: 1.720054633277e-01
[232/2145] Best orientation: ALMI-TINS | p-value: 6.469082543685e-02
[233/2145] Best orientation: TKIM-ALMI | p-value: 1.281427933463e-01
[234/2145] Best orientation: ALMI-TPIA | p-value: 2.041761539020e-01
[235/2145] Best orientation: ALMI-TRST | p-value: 1.072645589246e-02
[236/2145] Best orientation: ALMI-UNIC | p-value: 4.962619762559e-02
[237/2145] Best orientation: ALMI-WTON | p-value: 1.944507815391e-01
[238/2145] Best orientation: YPAS-ALMI | p-value: 5.466182389528e-04
[239/2145] Best orientation: ALMI-KMTR | p-value: 8.892795117816e-02
[240/2145] Best orientation: ALMI-MDKI | p-value: 1.791719577994e-01
[241/2145] Best orientation: ZINC-ALMI | p-value: 1.848698843322e-02
[242/2145] Best orientation: ALMI-PBID | p-value: 9.240259857786e-02
[243/2145] Best orientation: TDPM-ALMI | p-value: 7.783021205902e-05
[244/2145] Best orientation: ALMI-MOLI | p-value: 1.365175463405e-01
[245/2145] Best orientation: HKMU-ALMI | p-value: 1.711924205325e-02
[246/2145] Best orientation: KAYU-ALMI | p-value: 1.583260916643e-02
[247/2145] Best orientation: ALMI-SMKL | p-value: 5.038635145715e-02
[248/2145] Best orientation: ALMI-GGRP | p-value: 3.493328174691e-02
[249/2145] Best orientation: ALMI-OPMS | p-value: 1.006051661647e-01
[250/2145] Best orientation: ALMI-PURE | p-value: 4.663743925254e-02
[251/2145] Best orientation: ALMI-IFSH | p-value: 8.324312554474e-02
[252/2145] Best orientation: IFII-ALMI | p-value: 3.218313479737e-02
[253/2145] Best orientation: ALMI-ADMG | p-value: 9.556222360296e-02
[254/2145] Best orientation: ALMI-AGII | p-value: 1.612967209089e-02
[255/2145] Best orientation: ANTM-APLI | p-value: 6.899058552948e-01
[256/2145] Best orientation: ANTM-BAJA | p-value: 2.746151511593e-01
[257/2145] Best orientation: BMSR-ANTM | p-value: 3.991785363564e-01
[258/2145] Best orientation: BRPT-ANTM | p-value: 4.925177484751e-03
[259/2145] Best orientation: ANTM-BTON | p-value: 3.222312017163e-01
[260/2145] Best orientation: CITA-ANTM | p-value: 1.197240720585e-01
[261/2145] Best orientation: ANTM-CLPI | p-value: 2.285703618683e-01
[262/2145] Best orientation: DKFT-ANTM | p-value: 1.611086585109e-01
[263/2145] Best orientation: EKAD-ANTM | p-value: 1.334324324112e-01
[264/2145] Best orientation: ANTM-ESSA | p-value: 6.103767141590e-01
[265/2145] Best orientation: ANTM-ETWA | p-value: 5.565949726350e-01
[266/2145] Best orientation: ANTM-FPNI | p-value: 2.458032402795e-01
[267/2145] Best orientation: GDST-ANTM | p-value: 4.440475087967e-01
[268/2145] Best orientation: ANTM-IGAR | p-value: 2.497484375427e-01
[269/2145] Best orientation: ANTM-INAI | p-value: 7.344069597250e-01
[270/2145] Best orientation: INCI-ANTM | p-value: 4.092324707002e-01
[271/2145] Best orientation: ANTM-INCO | p-value: 7.413817221323e-01
[272/2145] Best orientation: INKP-ANTM | p-value: 2.665508765992e-01
[273/2145] Best orientation: INTD-ANTM | p-value: 3.201076518149e-01
[274/2145] Best orientation: INTP-ANTM | p-value: 9.933445835991e-03
[275/2145] Best orientation: ANTM-IPOL | p-value: 2.989259101572e-04
[276/2145] Best orientation: ANTM-ISSP | p-value: 2.202478161366e-01
[277/2145] Best orientation: ANTM-KDSI | p-value: 5.490344638673e-01
[278/2145] Best orientation: ANTM-KRAS | p-value: 6.864774592970e-01
[279/2145] Best orientation: LMSH-ANTM | p-value: 5.640989269105e-04
[280/2145] Best orientation: ANTM-LTLS | p-value: 5.773138689014e-01
[281/2145] Best orientation: ANTM-MDKA | p-value: 5.695651011918e-01
[282/2145] Best orientation: ANTM-NIKL | p-value: 5.648114405299e-01
[283/2145] Best orientation: OKAS-ANTM | p-value: 3.653848731630e-02
[284/2145] Best orientation: PICO-ANTM | p-value: 1.398569504235e-02
[285/2145] Best orientation: ANTM-PSAB | p-value: 5.880869745494e-01
[286/2145] Best orientation: SMBR-ANTM | p-value: 4.113954127684e-01
[287/2145] Best orientation: SMCB-ANTM | p-value: 3.109132984811e-02
[288/2145] Best orientation: SMGR-ANTM | p-value: 3.642373969477e-01
[289/2145] Best orientation: ANTM-SPMA | p-value: 4.465290658245e-01
[290/2145] Best orientation: ANTM-SQMI | p-value: 5.627711492734e-01

In [66]:
list_top5 = [df.assign(Sektor=s) for s, df in top5_per_sektor.items() if not df.empty]

if list_top5:
    all_top5 = pd.concat(list_top5, ignore_index=True)
    all_top5 = all_top5[["Sektor", "Saham_Y", "Saham_X", "Test_Statistic", "P_Value"]]

    print("\n=== Rekap Semua Top 5 Per Sektor ===")
    print(all_top5.to_string(index=True))

    all_top5.to_csv("top5_pairs_per_sektor_twoway.csv", index=False)
    print("\nDisimpan ke top5_pairs_per_sektor_twoway.csv")
else:
    print("\nTidak ada pasangan yang signifikan secara statistik di seluruh sektor.")

=== Rekap Semua Top 5 Per Sektor ===
                        Sektor Saham_Y Saham_X  Test_Statistic       P_Value
0                  barang_baku    HKMU    ESSA       -7.203201  2.794950e-09
1                  barang_baku    HKMU    UNIC       -7.174413  3.279544e-09
2                  barang_baku    IFII    PSAB       -7.022953  7.566726e-09
3                  barang_baku    HKMU    ALKA       -7.008629  8.185508e-09
4                  barang_baku    HKMU    SMGR       -6.991186  9.006706e-09
5   barang_konsumsi_non_primer    TELE    PMJS       -7.134718  4.086396e-09
6   barang_konsumsi_non_primer    TELE    MAPI       -6.947457  1.143995e-08
7   barang_konsumsi_non_primer    TELE    BOGA       -6.869886  1.745015e-08
8   barang_konsumsi_non_primer    GDYR    GLOB       -6.687265  4.666227e-08
9   barang_konsumsi_non_primer    TELE    PANR       -6.609983  7.042181e-08
10      barang_konsumsi_primer    SKBM    MGRO       -6.524798  1.104726e-07
11      barang_konsumsi_primer    SKBM    SIPD       -6.478895  1.405947e-07
12      barang_konsumsi_primer    DLTA    ITIC       -6.307338  3.428143e-07
13      barang_konsumsi_primer    SKBM    DSFI       -6.242810  4.773575e-07
14      barang_konsumsi_primer    SKBM    LSIP       -6.075444  1.114082e-06
15                      energi    WOWS    BOSS       -6.561266  9.114517e-08
16                      energi    WOWS    MYOH       -6.384810  2.296708e-07
17                      energi    WOWS    RUIS       -6.325920  3.115060e-07
18                      energi    WOWS    SHIP       -6.227498  5.161944e-07
19                      energi    WOWS    ABMM       -6.183254  6.466020e-07
20                  industrial    SOSS    SKRN       -5.157579  8.362211e-05
21                  industrial    SOSS    KOIN       -5.155851  8.425482e-05
22                  industrial    SOSS    IKBI       -5.096618  1.089431e-04
23                  industrial    APII    SPTO       -5.001725  1.634445e-04
24                  industrial    KBLI    UNTR       -4.949741  2.034625e-04
25               infrastruktur    MTRA    JAST      -13.753527  1.001591e-24
26               infrastruktur    TOPS    KEEN      -12.961068  3.364566e-23
27               infrastruktur    TOPS    TLKM      -12.894618  4.595571e-23
28               infrastruktur    TOPS    IPCC      -12.786725  7.664916e-23
29               infrastruktur    TOPS    CMNP      -12.565908  2.227770e-22
30                   kesehatan    MIKA    PRIM       -4.449124  1.482832e-03
31                   kesehatan    MIKA    MERK       -4.027558  6.557515e-03
32                   kesehatan    MIKA    KLBF       -3.983884  7.570456e-03
33                   kesehatan    MIKA    HEAL       -3.884667  1.041326e-02
34                   kesehatan    KAEF    INAF       -3.637394  2.200845e-02
35                    keuangan    JMAS    BBRI       -7.208657  2.711439e-09
36                    keuangan    BGTG    ARTO       -7.190733  2.995457e-09
37                    keuangan    JMAS    BBNI       -7.167221  3.413020e-09
38                    keuangan    JMAS    BMRI       -7.001197  8.525956e-09
39                    keuangan    TRUS    APIC       -6.977895  9.686574e-09
40                    properti    NZIA    PAMG       -7.465253  6.435182e-10
41                    properti    NZIA    LPCK       -6.784786  2.764845e-08
42                    properti    KIJA    PAMG       -6.198234  5.992002e-07
43                    properti    NZIA    JRPT       -6.121182  8.852037e-07
44                    properti    NZIA    CTRA       -5.991871  1.690359e-06
45                   teknologi    SKYB    KIOS      -15.005002  9.156219e-27
46                   teknologi    SKYB    ATIC      -13.966259  4.173730e-25
47                   teknologi    SKYB    DIVA      -13.531688  2.575423e-24
48                   teknologi    SKYB    GLVA      -12.630762  1.624036e-22
49                   teknologi    SKYB    MTDL      -12.016449  3.533415e-21
50   transportasi_dan_logistik    AKSI    HELI       -5.658900  8.511132e-06
51   transportasi_dan_logistik    LRNA    JAYA       -4.520225  1.134219e-03
52   transportasi_dan_logistik    LRNA    WEHA       -4.498648  1.230951e-03
53   transportasi_dan_logistik    IMJS    ASSA       -4.401141  1.771943e-03
54   transportasi_dan_logistik    LRNA    BIRD       -4.291579  2.638910e-03

Disimpan ke top5_pairs_per_sektor_twoway.csv

In [69]:
top50_per_sektor = {}

for sektor, pair_df in cointegration_results.items():
    significant = pair_df[pair_df["P_Value"] < 0.05]
    top50 = significant.head(50).reset_index(drop=True)
    top50_per_sektor[sektor] = top50

    print(f"\n  → Top 50 cointegrated pairs ({sektor}):")
    if top50.empty:
        print("    Tidak ada pair cointegrated (p < 0.05)")
    else:
        print(top50[["Saham_Y", "Saham_X", "P_Value"]].to_string())

list_top50 = [df.assign(Sektor=s) for s, df in top50_per_sektor.items() if not df.empty]

if list_top50:
    all_top50 = pd.concat(list_top50, ignore_index=True)
    all_top50 = all_top50[["Sektor", "Saham_Y", "Saham_X", "Test_Statistic", "P_Value"]]

    print("\n=== Rekap Semua Top 50 Per Sektor ===")
    print(all_top50.to_string(index=True))

    all_top50.to_csv("top50_pairs_per_sektor_twoway.csv", index=False)
    print("\nDisimpan ke top50_pairs_per_sektor_twoway.csv")

  → Top 50 cointegrated pairs (barang_baku):
   Saham_Y Saham_X       P_Value
0     HKMU    ESSA  2.794950e-09
1     HKMU    UNIC  3.279544e-09
2     IFII    PSAB  7.566726e-09
3     HKMU    ALKA  8.185508e-09
4     HKMU    SMGR  9.006706e-09
5     HKMU    SMKL  1.164236e-08
6     HKMU    IFSH  1.212467e-08
7     HKMU    APLI  1.237380e-08
8     HKMU    KMTR  1.590022e-08
9     HKMU    BTON  2.302807e-08
10    HKMU    ALDO  4.720005e-08
11    HKMU    AKPI  5.951333e-08
12    HKMU    MDKA  6.016116e-08
13    HKMU    SMCB  6.115270e-08
14    IFII    PURE  6.734441e-08
15    HKMU    YPAS  6.813101e-08
16    PICO    ALMI  7.542519e-08
17    IFII    MOLI  7.896074e-08
18    HKMU    ISSP  8.383667e-08
19    HKMU    LMSH  8.384074e-08
20    HKMU    GDST  1.374530e-07
21    YPAS    MDKA  1.586667e-07
22    IFII    TRST  2.176006e-07
23    IFII    AGII  2.940867e-07
24    IFII    BTON  5.470952e-07
25    HKMU    FPNI  6.323958e-07
26    IFII    INAI  6.730918e-07
27    HKMU    CLPI  1.086552e-06
28    IFII    AKPI  1.247453e-06
29    IFII    SQMI  1.453588e-06
30    YPAS    UNIC  1.634248e-06
31    YPAS    GGRP  1.764085e-06
32    HKMU    ANTM  2.042948e-06
33    YPAS    TRST  2.261850e-06
34    IFII    MDKA  2.277534e-06
35    YPAS    SMKL  2.384682e-06
36    IFII    SPMA  2.454617e-06
37    IFII    ESSA  3.393234e-06
38    YPAS    AKPI  3.726285e-06
39    TDPM    YPAS  5.309427e-06
40    IFII    CITA  5.671580e-06
41    IFII    TBMS  5.933954e-06
42    IFII    IGAR  6.393380e-06
43    IFII    UNIC  6.624580e-06
44    IFII    WTON  7.272018e-06
45    IFII    APLI  7.605351e-06
46    HKMU    MOLI  7.973707e-06
47    LMSH    IFSH  8.893378e-06
48    PICO    ETWA  1.073554e-05
49    IFII    BMSR  1.149428e-05

  → Top 50 cointegrated pairs (barang_konsumsi_non_primer):
   Saham_Y Saham_X       P_Value
0     TELE    PMJS  4.086396e-09
1     TELE    MAPI  1.143995e-08
2     TELE    BOGA  1.745015e-08
3     GDYR    GLOB  4.666227e-08
4     TELE    PANR  7.042181e-08
5     TELE    FILM  3.160319e-07
6     PBRX    MICE  6.001412e-07
7     TELE    CSAP  7.231548e-07
8     PZZA    TMPO  9.224561e-07
9     TELE    KPIG  1.027233e-06
10    GDYR    PZZA  1.037661e-06
11    TELE    MICE  1.427501e-06
12    GDYR    RALS  2.907232e-06
13    HRME    POLY  5.051223e-06
14    GDYR    KPIG  5.825204e-06
15    HRME    HRTA  5.931590e-06
16    GDYR    JIHD  6.281494e-06
17    JIHD    TFCO  6.541233e-06
18    HRME    EAST  6.648846e-06
19    HRME    SMSM  6.719936e-06
20    HRME    SCMA  7.973973e-06
21    HRME    LPPF  9.049769e-06
22    HRME    MAPI  9.407087e-06
23    HRME    MAPA  9.757622e-06
24    HRME    PANR  1.064789e-05
25    GDYR    DUCK  1.070791e-05
26    PBRX    KPIG  1.071106e-05
27    TELE    SMSM  1.090726e-05
28    HRME    KICI  1.162657e-05
29    GDYR    PDES  1.171114e-05
30    DUCK    PDES  1.349820e-05
31    HRME    AUTO  1.354313e-05
32    HRME    BOLA  1.384460e-05
33    PBRX    GWSA  1.412481e-05
34    TELE    SCMA  1.464571e-05
35    GDYR    PMJS  1.555475e-05
36    HRME    MAPB  1.715017e-05
37    GDYR    TELE  1.772057e-05
38    HRME    WOOD  1.882603e-05
39    HRME    BELL  1.888579e-05
40    GDYR    ARTA  1.959557e-05
41    GDYR    BOGA  1.985282e-05
42    GDYR    FAST  2.297492e-05
43    HRME    IMAS  2.312856e-05
44    GDYR    TFCO  2.335912e-05
45    DUCK    GWSA  2.365969e-05
46    PDES    TFCO  2.371149e-05
47    PBRX    GJTL  2.453471e-05
48    HRME    SLIS  2.534200e-05
49    PBRX    MAPB  2.649932e-05

  → Top 50 cointegrated pairs (barang_konsumsi_primer):
   Saham_Y Saham_X       P_Value
0     SKBM    MGRO  1.104726e-07
1     SKBM    SIPD  1.405947e-07
2     DLTA    ITIC  3.428143e-07
3     SKBM    DSFI  4.773575e-07
4     SKBM    LSIP  1.114082e-06
5     SKBM    WAPO  1.166685e-06
6     WICO    BUDI  1.466019e-06
7     SKBM    SIMP  1.875059e-06
8     SKBM    RANC  2.916016e-06
9     SKBM    PSGO  3.081804e-06
10    WICO    COCO  4.212877e-06
11    SKBM    HERO  4.788897e-06
12    SKBM    STTP  6.105336e-06
13    SKBM    GOOD  1.234978e-05
14    WICO    HMSP  1.399530e-05
15    SKBM    UNSP  1.679070e-05
16    SKBM    BEEF  1.694767e-05
17    WICO    GGRM  1.816497e-05
18    SKBM    JPFA  2.471936e-05
19    SKBM    SMAR  2.479405e-05
20    SKBM    KEJU  2.967600e-05
21    SKBM    AALI  3.998988e-05
22    SKBM    JAWA  4.064187e-05
23    SKBM    MYOR  4.757708e-05
24    SKBM    DAYA  5.279171e-05
25    SKBM    CLEO  5.360639e-05
26    SKBM    WIIM  5.797279e-05
27    SKBM    CEKA  5.998884e-05
28    SKBM    ULTJ  6.474232e-05
29    WICO    UNVR  7.008481e-05
30    SKBM    ICBP  7.202610e-05
31    SKBM    SSMS  7.381522e-05
32    SKBM    DSNG  8.021860e-05
33    SKBM    COCO  8.586157e-05
34    SKBM    HMSP  8.594920e-05
35    SKBM    TGKA  8.646789e-05
36    DLTA    ANJT  8.796644e-05
37    SKBM    FOOD  8.819301e-05
38    SKBM    ITIC  9.558657e-05
39    DLTA    PCAR  9.782774e-05
40    SKBM    GGRM  1.112183e-04
41    SKBM    MIDI  1.120351e-04
42    SKBM    MPPA  1.126975e-04
43    SKBM    CPIN  1.200281e-04
44    HMSP    GOOD  1.238086e-04
45    HMSP    CAMP  1.280853e-04
46    SKBM    ANJT  1.312859e-04
47    SKBM    TBLA  1.387486e-04
48    SKBM    KINO  1.394960e-04
49    SKBM    BUDI  1.443876e-04

  → Top 50 cointegrated pairs (energi):
   Saham_Y Saham_X       P_Value
0     WOWS    BOSS  9.114517e-08
1     WOWS    MYOH  2.296708e-07
2     WOWS    RUIS  3.115060e-07
3     WOWS    SHIP  5.161944e-07
4     WOWS    ABMM  6.466020e-07
5     WOWS    MEDC  9.983550e-07
6     WOWS    AKRA  1.257994e-06
7     WOWS    BSSR  1.409985e-06
8     WOWS    WINS  1.515248e-06
9     WOWS    GTBO  1.521638e-06
10    WOWS    FIRE  1.620340e-06
11    WOWS    ITMG  1.814990e-06
12    WOWS    ADRO  2.041308e-06
13    WOWS    PTBA  2.050832e-06
14    WOWS    ELSA  2.050835e-06
15    WOWS    KKGI  2.080860e-06
16    WOWS    ITMA  2.114904e-06
17    WOWS    SOCI  2.182279e-06
18    WOWS    MBSS  2.243217e-06
19    WOWS    RAJA  2.621998e-06
20    WOWS    SMMT  2.842193e-06
21    WOWS    BUMI  2.942364e-06
22    WOWS    DOID  3.475321e-06
23    WOWS    PTIS  3.552874e-06
24    WOWS    PSSI  3.728690e-06
25    WOWS    PTRO  3.777310e-06
26    WOWS    INDY  3.977050e-06
27    WOWS    APEX  4.007228e-06
28    WOWS    RIGS  4.600354e-06
29    WOWS    ENRG  4.824986e-06
30    WOWS    TOBA  5.127312e-06
31    WOWS    MBAP  5.766081e-06
32    DWGL    PTIS  9.744103e-06
33    WOWS    HRUM  1.178324e-05
34    WOWS    HITS  1.190793e-05
35    WOWS    TPMA  1.435428e-05
36    WOWS    KOPI  1.489836e-05
37    WOWS    SURE  2.175370e-05
38    KOPI    DWGL  3.938664e-05
39    WOWS    PGAS  4.534540e-05
40    WOWS    INPS  4.700911e-05
41    KOPI    GTBO  8.115724e-05
42    SOCI    TEBE  1.591001e-04
43    PGAS    INDY  4.030843e-04
44    WOWS    ARII  4.158497e-04
45    WOWS    DWGL  4.757965e-04
46    HRUM    MYOH  5.683996e-04
47    PGAS    PTBA  7.657402e-04
48    WOWS    TEBE  7.909651e-04
49    KOPI    WINS  8.547609e-04

  → Top 50 cointegrated pairs (industrial):
   Saham_Y Saham_X   P_Value
0     SOSS    SKRN  0.000084
1     SOSS    KOIN  0.000084
2     SOSS    IKBI  0.000109
3     APII    SPTO  0.000163
4     KBLI    UNTR  0.000203
5     KBLI    MFMI  0.000558
6     SPTO    CCSI  0.000572
7     SPTO    MLIA  0.000603
8     ARKA    ASII  0.000633
9     SPTO    AMFG  0.000883
10    APII    KBLM  0.001025
11    SPTO    MFMI  0.001117
12    SPTO    HEXA  0.001124
13    APII    ARKA  0.001142
14    SPTO    KOBX  0.001148
15    SPTO    BLUE  0.001148
16    KBLI    CCSI  0.001181
17    SPTO    IMPC  0.001280
18    APII    BLUE  0.001448
19    APII    SCCO  0.001516
20    SPTO    CAKK  0.001611
21    ARKA    KBLM  0.001626
22    VOKS    UNTR  0.001793
23    SPTO    SOSS  0.001839
24    SPTO    ARNA  0.002048
25    SOSS    LION  0.002055
26    APII    BHIT  0.002109
27    SPTO    SKRN  0.002131
28    SPTO    SCCO  0.002171
29    SPTO    IBFN  0.002212
30    APII    TOTO  0.002247
31    SPTO    IKBI  0.002308
32    SPTO    BHIT  0.002454
33    APII    CCSI  0.002504
34    VOKS    MFMI  0.002518
35    SPTO    UNTR  0.002545
36    SPTO    JTPE  0.002584
37    APII    AMFG  0.002662
38    APII    KOBX  0.002779
39    SPTO    LION  0.002789
40    APII    MLIA  0.002889
41    APII    ASGR  0.003071
42    APII    SINI  0.003128
43    APII    MARK  0.003242
44    TOTO    KOBX  0.003328
45    KBLM    SCCO  0.003401
46    TOTO    BLUE  0.003536
47    AMFG    IMPC  0.003694
48    APII    JTPE  0.003741
49    SPTO    KOIN  0.003901

  → Top 50 cointegrated pairs (infrastruktur):
   Saham_Y Saham_X       P_Value
0     MTRA    JAST  1.001591e-24
1     TOPS    KEEN  3.364566e-23
2     TOPS    TLKM  4.595571e-23
3     TOPS    IPCC  7.664916e-23
4     TOPS    CMNP  2.227770e-22
5     TOPS    LINK  4.354503e-22
6     TOPS    BALI  1.335778e-21
7     TOPS    PORT  2.035729e-21
8     TOPS    MPOW  3.075595e-21
9     TOPS    KARW  4.970820e-21
10    TOPS    OASA  1.520285e-20
11    TOPS    CENT  3.757491e-19
12    TOPS    ADHI  5.534063e-19
13    TOPS    PPRE  1.717711e-18
14    TOPS    ISAT  5.561037e-18
15    TOPS    GOLD  1.189946e-17
16    TOPS    GHON  2.807539e-16
17    TOPS    PTPP  7.599402e-16
18    TOPS    TBIG  1.993548e-15
19    TOPS    WIKA  9.767107e-15
20    TOPS    EXCL  1.128068e-14
21    TOPS    IPCM  1.828829e-14
22    TOPS    TOWR  1.003847e-13
23    TOPS    JSMR  5.526573e-13
24    TOPS    NRCA  1.666123e-12
25    TOPS    WEGE  1.760979e-12
26    TOPS    JKON  9.439997e-12
27    TOPS    IDPR  1.581865e-11
28    TOPS    JAST  1.911966e-11
29    TOPS    BUKK  2.732462e-10
30    TOPS    GMFI  3.394013e-10
31    TOPS    TOTL  6.106821e-10
32    TOPS    SSIA  7.231551e-10
33    MTRA    TOPS  6.720327e-09
34    MTRA    IDPR  7.866701e-08
35    MTRA    KEEN  1.151331e-07
36    MTRA    SSIA  2.007357e-07
37    GHON    TBIG  2.052752e-07
38    JAST    OASA  2.372749e-07
39    MTPS    GOLD  2.399606e-07
40    TOPS    ACST  3.091732e-07
41    ACST    ADHI  5.026541e-07
42    JAST    GOLD  5.451967e-07
43    MTRA    CMNP  5.862327e-07
44    JAST    PORT  5.893005e-07
45    TOPS    MTPS  1.010195e-06
46    MTRA    KARW  1.148804e-06
47    MTRA    BALI  1.592712e-06
48    POWR    TOTL  1.652476e-06
49    MTPS    IPCC  1.693134e-06

  → Top 50 cointegrated pairs (kesehatan):
  Saham_Y Saham_X   P_Value
0    MIKA    PRIM  0.001483
1    MIKA    MERK  0.006558
2    MIKA    KLBF  0.007570
3    MIKA    HEAL  0.010413
4    KAEF    INAF  0.022008
5    MIKA    SRAJ  0.031802
6    MIKA    SILO  0.037026
7    MIKA    PEHA  0.042094
8    MIKA    DVLA  0.049868

  → Top 50 cointegrated pairs (keuangan):
   Saham_Y Saham_X       P_Value
0     JMAS    BBRI  2.711439e-09
1     BGTG    ARTO  2.995457e-09
2     JMAS    BBNI  3.413020e-09
3     JMAS    BMRI  8.525956e-09
4     TRUS    APIC  9.686574e-09
5     JMAS    MCOR  1.668626e-08
6     JMAS    BTPN  1.994318e-08
7     JMAS    BBCA  2.328118e-08
8     JMAS    BBKP  2.530496e-08
9     JMAS    BACA  2.590068e-08
10    JMAS    BNLI  3.072426e-08
11    JMAS    NISP  3.184974e-08
12    JMAS    NICK  4.213175e-08
13    JMAS    AGRS  5.445155e-08
14    JMAS    BKSW  5.511936e-08
15    JMAS    LPPS  5.704025e-08
16    JMAS    BNGA  6.248678e-08
17    JMAS    SFAN  7.257641e-08
18    JMAS    CFIN  7.340629e-08
19    JMAS    DNAR  7.739797e-08
20    TRUS    YULE  9.417540e-08
21    JMAS    BBTN  9.641660e-08
22    JMAS    CASA  9.866195e-08
23    JMAS    PNIN  1.075509e-07
24    JMAS    PANS  1.132939e-07
25    JMAS    PNBN  1.593610e-07
26    JMAS    YULE  1.617434e-07
27    JMAS    BCAP  1.764517e-07
28    JMAS    PNLF  2.120929e-07
29    JMAS    AMAG  2.374875e-07
30    JMAS    VINS  2.519922e-07
31    ASDM    VINS  3.017060e-07
32    TRUS    SDRA  3.782560e-07
33    ASDM    BNLI  3.973954e-07
34    ASDM    AMAG  5.765902e-07
35    JMAS    WOMF  5.810577e-07
36    ASBI    DNET  9.280705e-07
37    ASDM    MCOR  1.106583e-06
38    JMAS    PEGE  1.142524e-06
39    JMAS    AGRO  1.156037e-06
40    JMAS    SDRA  1.214920e-06
41    JMAS    BBYB  1.254274e-06
42    ASDM    BACA  1.485045e-06
43    ASDM    BBHI  1.494763e-06
44    ASDM    FUJI  1.908318e-06
45    ASDM    STAR  2.054086e-06
46    JMAS    BGTG  2.150326e-06
47    JMAS    ARTO  2.275979e-06
48    ASDM    TRIM  2.466038e-06
49    JMAS    BJTM  2.498335e-06

  → Top 50 cointegrated pairs (properti):
   Saham_Y Saham_X       P_Value
0     NZIA    PAMG  6.435182e-10
1     NZIA    LPCK  2.764845e-08
2     KIJA    PAMG  5.992002e-07
3     NZIA    JRPT  8.852037e-07
4     NZIA    CTRA  1.690359e-06
5     NZIA    PANI  1.852427e-06
6     NZIA    SATU  1.859298e-06
7     NZIA    BAPA  3.250269e-06
8     NZIA    RISE  3.519329e-06
9     NZIA    CITY  3.927801e-06
10    NZIA    RDTX  4.315918e-06
11    NZIA    SMDM  8.752116e-06
12    NZIA    BSDE  2.491063e-05
13    NZIA    ASRI  2.711514e-05
14    NZIA    APLN  2.999125e-05
15    NZIA    POLI  4.332431e-05
16    NZIA    MMLP  4.876991e-05
17    PWON    CITY  8.010161e-05
18    NZIA    PWON  1.154238e-04
19    NZIA    LPKR  1.592135e-04
20    NZIA    BEST  1.695784e-04
21    MTLA    PAMG  2.110561e-04
22    NZIA    POLL  2.179280e-04
23    NZIA    PUDP  2.911239e-04
24    MTLA    BAPA  3.525962e-04
25    SMDM    BAPA  3.776795e-04
26    PWON    ASRI  5.117583e-04
27    NZIA    MTSM  6.856360e-04
28    DMAS    PAMG  1.383598e-03
29    NZIA    MTLA  1.456635e-03
30    PWON    LPCK  1.631075e-03
31    MTLA    SATU  1.654335e-03
32    LPKR    PAMG  2.009346e-03
33    NZIA    KIJA  2.043187e-03
34    KIJA    SATU  2.050359e-03
35    MTSM    PUDP  2.054599e-03
36    MTLA    SMDM  2.194193e-03
37    MTLA    LPKR  2.247413e-03
38    URBN    CTRA  2.281592e-03
39    MTLA    DILD  2.393824e-03
40    MTLA    MMLP  2.401130e-03
41    POLI    RISE  2.430962e-03
42    NZIA    SMRA  2.684574e-03
43    DMAS    RISE  2.737318e-03
44    URBN    BSDE  2.754548e-03
45    PAMG    RISE  2.885016e-03
46    KIJA    RISE  2.963307e-03
47    KIJA    PUDP  3.260744e-03
48    PAMG    POLI  4.083948e-03
49    KIJA    RDTX  4.193286e-03

  → Top 50 cointegrated pairs (teknologi):
   Saham_Y Saham_X       P_Value
0     SKYB    KIOS  9.156219e-27
1     SKYB    ATIC  4.173730e-25
2     SKYB    DIVA  2.575423e-24
3     SKYB    GLVA  1.624036e-22
4     SKYB    MTDL  3.533415e-21
5     SKYB    DMMX  6.570984e-21
6     SKYB    NFCX  1.046784e-20
7     SKYB    EMTK  5.194297e-18
8     SKYB    PTSN  7.032216e-17
9     SKYB    MCAS  7.124017e-17
10    SKYB    MLPT  1.564905e-09
11    SKYB    HDIT  7.427363e-07
12    ATIC    HDIT  3.228523e-05
13    ATIC    DIVA  1.931590e-04
14    ATIC    GLVA  4.464072e-04
15    KREN    HDIT  5.492120e-04
16    KREN    DIVA  8.312895e-04
17    SKYB    KREN  8.598055e-04
18    KREN    KIOS  9.071164e-04
19    KREN    NFCX  1.942702e-03
20    KREN    DMMX  2.399472e-03
21    KREN    MTDL  2.554169e-03
22    KREN    ATIC  3.103539e-03
23    KREN    EMTK  3.384481e-03
24    KREN    MCAS  3.728474e-03
25    KREN    GLVA  3.966579e-03
26    LUCK    GLVA  5.529288e-03
27    KREN    MLPT  7.641790e-03
28    SKYB    LUCK  7.791754e-03
29    KREN    PTSN  1.014161e-02
30    KIOS    DIVA  1.670203e-02
31    PTSN    MLPT  2.067430e-02
32    ATIC    LUCK  2.433579e-02
33    PTSN    DMMX  2.498936e-02
34    ATIC    PTSN  2.813498e-02
35    MLPT    DMMX  3.002176e-02
36    ATIC    EMTK  3.225214e-02
37    ATIC    MTDL  3.258652e-02
38    LUCK    DIVA  3.427112e-02
39    LUCK    KIOS  3.463698e-02
40    LUCK    HDIT  4.375849e-02
41    ATIC    DMMX  4.821202e-02

  → Top 50 cointegrated pairs (transportasi_dan_logistik):
   Saham_Y Saham_X   P_Value
0     AKSI    HELI  0.000009
1     LRNA    JAYA  0.001134
2     LRNA    WEHA  0.001231
3     IMJS    ASSA  0.001772
4     LRNA    BIRD  0.002639
5     BPTR    WEHA  0.003715
6     LRNA    NELY  0.003964
7     IMJS    JAYA  0.004110
8     LRNA    BPTR  0.004673
9     LRNA    IMJS  0.005060
10    LRNA    SMDR  0.006341
11    LRNA    TMAS  0.006773
12    BIRD    NELY  0.008152
13    LRNA    ASSA  0.008707
14    TNCA    ASSA  0.009302
15    AKSI    TRUK  0.011070
16    BIRD    TMAS  0.011157
17    LRNA    TNCA  0.014203
18    LRNA    HELI  0.015336
19    SAFE    WEHA  0.016471
20    LRNA    SAFE  0.016817
21    LRNA    AKSI  0.017229
22    LRNA    TRUK  0.020153
23    BPTR    TNCA  0.024195
24    SAFE    BPTR  0.024291
25    IMJS    TNCA  0.024647
26    BIRD    SMDR  0.026510
27    IMJS    TRUK  0.032402
28    BPTR    JAYA  0.037682
29    SAFE    TNCA  0.039462
30    SAFE    JAYA  0.039532
31    IMJS    BPTR  0.041235
32    SAFE    TMAS  0.041909
33    BIRD    AKSI  0.045628

=== Rekap Semua Top 50 Per Sektor ===
                         Sektor Saham_Y Saham_X  Test_Statistic       P_Value
0                   barang_baku    HKMU    ESSA       -7.203201  2.794950e-09
1                   barang_baku    HKMU    UNIC       -7.174413  3.279544e-09
2                   barang_baku    IFII    PSAB       -7.022953  7.566726e-09
3                   barang_baku    HKMU    ALKA       -7.008629  8.185508e-09
4                   barang_baku    HKMU    SMGR       -6.991186  9.006706e-09
5                   barang_baku    HKMU    SMKL       -6.944244  1.164236e-08
6                   barang_baku    HKMU    IFSH       -6.936805  1.212467e-08
7                   barang_baku    HKMU    APLI       -6.933076  1.237380e-08
8                   barang_baku    HKMU    KMTR       -6.887015  1.590022e-08
9                   barang_baku    HKMU    BTON       -6.818669  2.302807e-08
10                  barang_baku    HKMU    ALDO       -6.685120  4.720005e-08
11                  barang_baku    HKMU    AKPI       -6.641651  5.951333e-08
12                  barang_baku    HKMU    MDKA       -6.639617  6.016116e-08
13                  barang_baku    HKMU    SMCB       -6.636544  6.115270e-08
14                  barang_baku    IFII    PURE       -6.618400  6.734441e-08
15                  barang_baku    HKMU    YPAS       -6.616213  6.813101e-08
16                  barang_baku    PICO    ALMI       -6.597041  7.542519e-08
17                  barang_baku    IFII    MOLI       -6.588395  7.896074e-08
18                  barang_baku    HKMU    ISSP       -6.577076  8.383667e-08
19                  barang_baku    HKMU    LMSH       -6.577067  8.384074e-08
20                  barang_baku    HKMU    GDST       -6.483207  1.374530e-07
21                  barang_baku    YPAS    MDKA       -6.455796  1.586667e-07
22                  barang_baku    IFII    TRST       -6.395204  2.176006e-07
23                  barang_baku    IFII    AGII       -6.337067  2.940867e-07
24                  barang_baku    IFII    BTON       -6.216099  5.470952e-07
25                  barang_baku    HKMU    FPNI       -6.187628  6.323958e-07
26                  barang_baku    IFII    INAI       -6.175344  6.730918e-07
27                  barang_baku    HKMU    CLPI       -6.080433  1.086552e-06
28                  barang_baku    IFII    AKPI       -6.052863  1.247453e-06
29                  barang_baku    IFII    SQMI       -6.022221  1.453588e-06
30                  barang_baku    YPAS    UNIC       -5.998671  1.634248e-06
31                  barang_baku    YPAS    GGRP       -5.983264  1.764085e-06
32                  barang_baku    HKMU    ANTM       -5.953603  2.042948e-06
33                  barang_baku    YPAS    TRST       -5.932965  2.261850e-06
34                  barang_baku    IFII    MDKA       -5.931562  2.277534e-06
35                  barang_baku    YPAS    SMKL       -5.922221  2.384682e-06
36                  barang_baku    IFII    SPMA       -5.916342  2.454617e-06
37                  barang_baku    IFII    ESSA       -5.850170  3.393234e-06
38                  barang_baku    YPAS    AKPI       -5.830928  3.726285e-06
39                  barang_baku    TDPM    YPAS       -5.757695  5.309427e-06
40                  barang_baku    IFII    CITA       -5.743964  5.671580e-06
41                  barang_baku    IFII    TBMS       -5.734538  5.933954e-06
42                  barang_baku    IFII    IGAR       -5.718968  6.393380e-06

## Pair

In [71]:
COINTEGRATION_PAIRS = [
    "SOSS-SKRN", "KOPI-DWGL", "PICO-ALMI", "JAST-OASA",
    "AKSI-HELI", "JMAS-BBRI", "NZIA-PAMG", "ATIC-DIVA",
    "SKBM-MGRO", "GDYR-GLOB", "MIKA-PRIM",
]

PEARSON_SPEARMAN_PAIRS = [
    "HEXA-IMPC",
    "ITMG-ADRO",
    "SPMA-UNIC",
    "ADHI-PTPP",
    "SMDR-TMAS",
    "PNBN-PNLF", "BBNI-BMRI",
    "POLL-URBN",
    "MLPT-DMMX",
    "ADES-AMRT",
    "MAPI-PANR",
    "INAF-KAEF",
]

# Pair Trading (dengan grid search)

In [76]:
import os
import numpy as np
import pandas as pd
import statsmodels.api as sm
from statsmodels.regression.rolling import RollingOLS
from statsmodels.tsa.stattools import adfuller
import yfinance as yf
from itertools import product as iproduct
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

os.makedirs("BT_RSI", exist_ok=True)

# ─── PAIR CLASSIFICATION ───────────────────────────────────────────────────────
COINTEGRATION_PAIRS = [
    "SOSS-SKRN", "KOPI-DWGL", "PICO-ALMI", "JAST-OASA",
    "AKSI-HELI", "JMAS-BBRI", "NZIA-PAMG", "ATIC-DIVA",
    "SKBM-MGRO", "GDYR-GLOB", "MIKA-PRIM",
]

PEARSON_SPEARMAN_PAIRS = [
    "HEXA-IMPC",
    "ITMG-ADRO",
    "SPMA-UNIC",
    "ADHI-PTPP",
    "SMDR-TMAS",
    "PNBN-PNLF", "BBNI-BMRI",
    "POLL-URBN",
    "MLPT-DMMX",
    "ADES-AMRT",
    "MAPI-PANR",
    "INAF-KAEF",
]

all_pairs        = COINTEGRATION_PAIRS + PEARSON_SPEARMAN_PAIRS
COINTEGRATION_SET = set(COINTEGRATION_PAIRS)

# ─── DATE RANGES ──────────────────────────────────────────────────────────────
data_start  = "2021-06-01"   # buffer untuk Rolling OLS
train_start = "2022-01-01"
train_end   = "2023-12-31"
test_start  = "2024-01-01"
test_end    = "2025-12-31"

# ─── GRID SEARCH PARAMETERS ───────────────────────────────────────────────────
entry_thresholds = [1.5, 2.0, 2.5]
exit_thresholds  = [0.0, 0.25, 0.5]
window_list      = [20, 40, 60]

sl_tp_pairs = [
    (0.02, 0.03), (0.02, 0.04),
    (0.03, 0.045), (0.03, 0.06),
    (0.04, 0.06), (0.04, 0.08),
    (0.05, 0.075), (0.05, 0.10),
    (0.03, 999999), (0.05, 999999), (0.07, 999999)
]

rsi_periods    = [7, 10, 14]
rsi_thresholds = [25, 30, 35, 40]

MIN_TRAIN_TRADES = 10
OLS_WINDOW       = 60

# ─── HELPER: Tentukan arah Y/X berdasarkan ADF p-value residual OLS ──────────
def determine_direction_by_adf(price_a, price_b, ticker_a, ticker_b):
    def ols_residual_adf(dep, indep):
        X_const  = sm.add_constant(indep)
        model    = sm.OLS(dep, X_const).fit()
        residual = model.resid
        try:
            adf_result = adfuller(residual.dropna(), autolag="AIC")
            return float(adf_result[1])
        except Exception:
            return 1.0

    pval_ab = ols_residual_adf(price_a, price_b)
    pval_ba = ols_residual_adf(price_b, price_a)

    if pval_ab <= pval_ba:
        return price_a, price_b, ticker_a, ticker_b, pval_ab, pval_ba, "AB"
    else:
        return price_b, price_a, ticker_b, ticker_a, pval_ba, pval_ab, "BA"

# ─── HELPERS ──────────────────────────────────────────────────────────────────
def fmt_sl_tp(v):
    return "Disabled" if v >= 999 else f"{v*100:.0f}%"

def calc_rsi(series, period):
    delta    = series.diff()
    gain     = delta.clip(lower=0)
    loss     = -delta.clip(upper=0)
    sum_gain = gain.rolling(window=period).sum()
    sum_loss = loss.rolling(window=period).sum()
    total    = (sum_gain + sum_loss).replace(0, np.nan)
    return (sum_gain / total) * 100

def calc_zscore(df_in, win):
    spread = df_in["Dynamic_Spread"]
    mean   = spread.rolling(win).mean()
    std    = spread.rolling(win).std()
    return spread, (spread - mean) / std

def run_backtest(df, z_series, z_a, z_b, z_ex, sl, tp,
                 rsi_y=None, rsi_x=None, rsi_threshold=None):
    use_rsi  = (rsi_y is not None) and (rsi_x is not None) and (rsi_threshold is not None)
    position = pd.Series(0, index=df.index, dtype=int)
    exit_rsn = pd.Series("", index=df.index, dtype=object)
    entry_pr = None
    active_p = 0

    for i in range(1, len(df)):
        idx = df.index[i]
        z   = z_series.iloc[i]
        py  = df["Y"].iloc[i]
        px  = df["X"].iloc[i]

        if pd.isna(z):
            continue

        exit_reason = ""
        closed      = False

        if active_p != 0 and entry_pr is not None:
            cur_price       = py if active_p == 1 else px
            gross_pnl       = (cur_price - entry_pr) / entry_pr
            transaction_fee = 0.004
            pnl             = gross_pnl - transaction_fee

            if pnl <= -sl:
                active_p = 0; entry_pr = None; exit_reason = "SL"; closed = True
            elif pnl >= tp:
                active_p = 0; entry_pr = None; exit_reason = "TP"; closed = True

            if not closed and abs(z) < z_ex:
                active_p = 0; entry_pr = None; exit_reason = "Z-Exit"; closed = True

            if not closed and i == len(df) - 1:
                active_p = 0; entry_pr = None; exit_reason = "End of Data"; closed = True

        if active_p == 0 and not closed and i < len(df) - 1:
            if z < z_b:
                rsi_ok = True
                if use_rsi:
                    ry     = rsi_y.iloc[i]
                    rsi_ok = (not pd.isna(ry)) and (ry <= rsi_threshold)
                if rsi_ok:
                    active_p = 1; entry_pr = py
            elif z > z_a:
                rsi_ok = True
                if use_rsi:
                    rx     = rsi_x.iloc[i]
                    rsi_ok = (not pd.isna(rx)) and (rx <= rsi_threshold)
                if rsi_ok:
                    active_p = -1; entry_pr = px

        position.iloc[i] = active_p
        exit_rsn.iloc[i] = exit_reason

    prev_pos  = position.shift(1).fillna(0)
    strat_ret = pd.Series(0.0, index=df.index)
    strat_ret[prev_pos == 1]  = df["Ret_Y"]
    strat_ret[prev_pos == -1] = df["Ret_X"]
    strat_ret = strat_ret.fillna(0)

    equity  = (1 + strat_ret).cumprod()
    mean_d  = strat_ret.mean()
    std_d   = strat_ret.std()

    return {
        "position":   position,
        "exit_rsn":   exit_rsn,
        "strat_ret":  strat_ret,
        "equity":     equity,
        "sharpe":     0 if std_d == 0 else (mean_d / std_d) * np.sqrt(252),
        "total_ret":  equity.iloc[-1] - 1,
        "mdd":        (equity / equity.cummax() - 1).min(),
        "win_rate":   (strat_ret > 0).sum() / max(1, (strat_ret != 0).sum()),
        "volatility": std_d * np.sqrt(252),
        "n_trades":   int(((position != 0) & (position != position.shift(1))).sum()),
        "n_sl":       (exit_rsn == "SL").sum(),
        "n_tp":       (exit_rsn == "TP").sum(),
        "n_ze":       (exit_rsn == "Z-Exit").sum(),
    }

def build_trade_log(df, res):
    trade_log  = []
    in_trade   = False
    entry_date = entry_pos = entry_y = entry_x = None

    for i in range(1, len(df)):
        prev = res["position"].iloc[i-1]
        curr = res["position"].iloc[i]
        if prev == 0 and curr != 0:
            in_trade   = True
            entry_date = df.index[i]
            entry_pos  = curr
            entry_y    = float(df["Y"].iloc[i])
            entry_x    = float(df["X"].iloc[i])
        elif prev != 0 and curr == 0 and in_trade:
            exit_date = df.index[i]
            exit_y    = float(df["Y"].iloc[i])
            exit_x    = float(df["X"].iloc[i])
            gross_pnl = (exit_y - entry_y)/entry_y if entry_pos == 1 else (exit_x - entry_x)/entry_x
            pnl       = gross_pnl - 0.004
            exit_r    = res["exit_rsn"].iloc[i]
            trade_log.append([
                entry_date.date(), exit_date.date(),
                "Long Y" if entry_pos == 1 else "Long X",
                round(entry_y,4), round(exit_y,4),
                round(entry_x,4), round(exit_x,4),
                f"{pnl*100:.2f}%", exit_r,
                (exit_date - entry_date).days
            ])
            in_trade = False

    if in_trade and entry_date is not None:
        exit_date = df.index[-1]
        exit_y    = float(df["Y"].iloc[-1])
        exit_x    = float(df["X"].iloc[-1])
        gross_pnl = (exit_y - entry_y)/entry_y if entry_pos == 1 else (exit_x - entry_x)/entry_x
        pnl       = gross_pnl - 0.004
        trade_log.append([
            entry_date.date(), exit_date.date(),
            "Long Y" if entry_pos == 1 else "Long X",
            round(entry_y,4), round(exit_y,4),
            round(entry_x,4), round(exit_x,4),
            f"{pnl*100:.2f}%", "End of Data",
            (exit_date - entry_date).days
        ])
    return trade_log

def make_styles():
    return {
        "header_font":    Font(name="Arial", bold=True, color="FFFFFF"),
        "header_fill":    PatternFill("solid", start_color="1F4E79"),
        "center_align":   Alignment(horizontal="center"),
        "left_align":     Alignment(horizontal="left"),
        "thin_border":    Border(left=Side(style="thin"), right=Side(style="thin"),
                                 top=Side(style="thin"),  bottom=Side(style="thin")),
        "green_fill":     PatternFill("solid", start_color="E2EFDA"),
        "red_fill":       PatternFill("solid", start_color="FFDAD9"),
        "title_fill":     PatternFill("solid", start_color="1F4E79"),
        "section_fill":   PatternFill("solid", start_color="2E75B6"),
        "label_fill":     PatternFill("solid", start_color="D6E4F0"),
        "gold_fill":      PatternFill("solid", start_color="FFF2CC"),
        "gs_fill":        PatternFill("solid", start_color="375623"),
        "buy_y_fill":     PatternFill("solid", start_color="DDEEFF"),
        "buy_x_fill":     PatternFill("solid", start_color="E8F5E9"),
        "exit_fill":      PatternFill("solid", start_color="FFF9C4"),
        "hold_fill":      PatternFill("solid", start_color="FFFFFF"),
        "rsi_sect_fill":  PatternFill("solid", start_color="7030A0"),
        "rsi_label_fill": PatternFill("solid", start_color="EAD8F5"),
        "better_fill":    PatternFill("solid", start_color="C6EFCE"),
        "worse_fill":     PatternFill("solid", start_color="FFDAD9"),
    }

def style_header_row(ws, s):
    for cell in ws[1]:
        cell.font      = s["header_font"]
        cell.fill      = s["header_fill"]
        cell.alignment = s["center_align"]
        cell.border    = s["thin_border"]

def auto_col_width(ws, extra=4):
    for col in ws.columns:
        width = max(len(str(c.value or "")) for c in col) + extra
        ws.column_dimensions[get_column_letter(col[0].column)].width = width

def write_excel(wb, A, B, df, res_base, res_rsi, tlog_base, tlog_rsi, gs_base_df, gs_rsi_df,
                window, z_atas, z_exit, sl_best, tp_best, rsi_period_best, rsi_thresh_best,
                rsi_y_series=None, rsi_x_series=None, tlog_train_base=None, tlog_train_rsi=None,
                pair_type="cointegration", direction_info=None):

    s    = make_styles()
    bh_y = df["BH_Y"].iloc[-1] - 1
    bh_x = df["BH_X"].iloc[-1] - 1
    test_start_str = df.index[0].strftime('%Y-%m-%d')
    test_end_str   = df.index[-1].strftime('%Y-%m-%d')

    ws1 = wb.active
    ws1.title = "Comparison Summary"

    direction_label = "Cointegration (pre-set)"
    if pair_type == "pearson_spearman" and direction_info is not None:
        pval_chosen = direction_info["pval_chosen"]
        pval_alt    = direction_info["pval_alt"]
        direction_label = (f"Pearson/Spearman → ADF: {A}~{B}={pval_chosen:.4f} vs "
                           f"{B}~{A}={pval_alt:.4f} → pilih {direction_info['dir_code']}")

    rows = [
        ["PAIR TRADING — STRATEGY EVALUATION (TEST DATA)", "", "", ""],
        ["", "", "", ""],
        ["Metric", "Base Strategy", "RSI-Filtered", "Δ (RSI − Base)"],
        ["Total Return (%)", f"{res_base['total_ret']*100:.2f}%", f"{res_rsi['total_ret']*100:.2f}%", f"{(res_rsi['total_ret']-res_base['total_ret'])*100:.2f}%"],
        ["Sharpe Ratio", f"{res_base['sharpe']:.4f}", f"{res_rsi['sharpe']:.4f}", f"{res_rsi['sharpe']-res_base['sharpe']:.4f}"],
        ["Max Drawdown (%)", f"{res_base['mdd']*100:.2f}%", f"{res_rsi['mdd']*100:.2f}%", f"{(res_rsi['mdd']-res_base['mdd'])*100:.2f}%"],
        ["Win Rate (%)", f"{res_base['win_rate']*100:.2f}%", f"{res_rsi['win_rate']*100:.2f}%", f"{(res_rsi['win_rate']-res_base['win_rate'])*100:.2f}%"],
        ["Annual Volatility (%)", f"{res_base['volatility']*100:.2f}%", f"{res_rsi['volatility']*100:.2f}%", f"{(res_rsi['volatility']-res_base['volatility'])*100:.2f}%"],
        ["Total Trades", len(tlog_base), len(tlog_rsi), len(tlog_rsi) - len(tlog_base)],
        ["Avg Hold Days", f"{sum(t[9] for t in tlog_base)/max(1,len(tlog_base)):.1f}", f"{sum(t[9] for t in tlog_rsi)/max(1,len(tlog_rsi)):.1f}", ""],
        ["Best Trade", f"{max((float(t[7].replace('%','')) for t in tlog_base),default=0):.2f}%", f"{max((float(t[7].replace('%','')) for t in tlog_rsi),default=0):.2f}%", ""],
        ["Worst Trade", f"{min((float(t[7].replace('%','')) for t in tlog_base),default=0):.2f}%", f"{min((float(t[7].replace('%','')) for t in tlog_rsi),default=0):.2f}%", ""],
        ["Avg Trade Return", f"{sum(float(t[7].replace('%','')) for t in tlog_base)/max(1,len(tlog_base)):.2f}%", f"{sum(float(t[7].replace('%','')) for t in tlog_rsi)/max(1,len(tlog_rsi)):.2f}%", ""],
        ["TP Hits", res_base['n_tp'], res_rsi['n_tp'], res_rsi['n_tp'] - res_base['n_tp']],
        ["SL Hits", res_base['n_sl'], res_rsi['n_sl'], res_rsi['n_sl'] - res_base['n_sl']],
        ["Z-Exits", res_base['n_ze'], res_rsi['n_ze'], res_rsi['n_ze'] - res_base['n_ze']],
        ["", "", "", ""],
        ["BENCHMARK (TEST DATA)", "", "", ""],
        [f"Buy & Hold Y ({A})", f"{bh_y*100:.2f}%", "", ""],
        [f"Buy & Hold X ({B})", f"{bh_x*100:.2f}%", "", ""],
        ["vs B&H Y (Base)",  f"{(res_base['total_ret']-bh_y)*100:.2f}%", "", ""],
        ["vs B&H Y (RSI)",   f"{(res_rsi['total_ret']-bh_y)*100:.2f}%",  "", ""],
        ["", "", "", ""],
        ["PARAMETERS USED (Optimized on Train)", "", "", ""],
        ["Stock Y (Dependen)", A, "", ""],
        ["Stock X (Independen)", B, "", ""],
        ["Pair Type", pair_type.replace("_", "/").title(), "", ""],
        ["Direction Selection", direction_label, "", ""],
        ["Train Period", f"{train_start} → {train_end}", "", ""],
        ["Test Period (OOS)", f"{test_start_str} → {test_end_str}", "", ""],
        ["z_entry (±)", z_atas, "", ""],
        ["z_exit", z_exit, "", ""],
        ["Z-Score Window", window, "", ""],
        ["Stop Loss (best)", fmt_sl_tp(sl_best), "", ""],
        ["Take Profit (best)", fmt_sl_tp(tp_best), "", ""],
        ["Transaction Fee", "0.40% per Round-Trip", "", ""],
        ["Hedge Ratio Model", "Dynamic (Rolling OLS, win=60)", "", ""],
        ["RR Ratio", f"1 : {tp_best/sl_best:.1f}" if sl_best < 999 and tp_best < 999 else "N/A", "", ""],
        ["RSI Period (best)", rsi_period_best, "", ""],
        ["RSI Threshold (best)", rsi_thresh_best, "", ""],
    ]

    for row_data in rows:
        ws1.append(row_data)

    metric_rows_delta = {
        "Total Return (%)": "higher_better", "Sharpe Ratio": "higher_better",
        "Max Drawdown (%)": "lower_better", "Win Rate (%)": "higher_better",
        "Annual Volatility (%)": "lower_better", "Total Trades": "neutral",
        "TP Hits": "higher_better", "SL Hits": "lower_better", "Z-Exits": "neutral",
    }

    label_rows = [
        "Avg Hold Days","Best Trade","Worst Trade","Avg Trade Return",
        f"Buy & Hold Y ({A})", f"Buy & Hold X ({B})",
        "vs B&H Y (Base)", "vs B&H Y (RSI)",
        "Stock Y (Dependen)", "Stock X (Independen)",
        "Pair Type", "Direction Selection",
        "Train Period", "Test Period (OOS)",
        "z_entry (±)", "z_exit", "Z-Score Window",
        "Stop Loss (best)", "Take Profit (best)", "Transaction Fee",
        "Hedge Ratio Model", "RR Ratio", "RSI Period (best)", "RSI Threshold (best)"
    ]

    for row in ws1.iter_rows(min_row=1, max_row=ws1.max_row):
        label = str(row[0].value or "")
        for cell in row:
            cell.border = s["thin_border"]; cell.alignment = s["left_align"]; cell.font = Font(name="Arial", size=11)

        if label == "PAIR TRADING — STRATEGY EVALUATION (TEST DATA)":
            for cell in row:
                cell.font = Font(name="Arial", bold=True, size=13, color="FFFFFF")
                cell.fill = s["title_fill"]
            ws1.merge_cells(f"A{row[0].row}:D{row[0].row}")
        elif label == "Metric":
            for cell in row:
                cell.font = Font(name="Arial", bold=True, color="FFFFFF")
                cell.fill = s["header_fill"]
                cell.alignment = s["center_align"]
        elif label in ["BENCHMARK (TEST DATA)", "PARAMETERS USED (Optimized on Train)"]:
            for cell in row:
                cell.font = Font(name="Arial", bold=True, color="FFFFFF")
                cell.fill = s["rsi_sect_fill"]
            ws1.merge_cells(f"A{row[0].row}:D{row[0].row}")
        elif label in metric_rows_delta:
            row[0].fill = s["label_fill"]
            row[0].font = Font(name="Arial", bold=True, size=11)
            direction = metric_rows_delta[label]
            if direction != "neutral":
                try:
                    dv = float(str(row[3].value).replace("%",""))
                    if dv != 0:
                        better = (direction == "higher_better" and dv > 0) or (direction == "lower_better" and dv < 0)
                        row[3].fill = s["better_fill"] if better else s["worse_fill"]
                except: pass
        elif label in label_rows:
            row[0].fill = s["label_fill"]
            row[0].font = Font(name="Arial", bold=True, size=11)

    for i, w in enumerate([38, 20, 20, 18], 1):
        ws1.column_dimensions[get_column_letter(i)].width = w

    tlog_headers = ["Entry Date","Exit Date","Direction","Entry Y","Exit Y","Entry X","Exit X","Net PnL","Exit Reason","Hold Days"]
    log_sheets   = [("Train Log (Base)", tlog_train_base), ("Train Log (RSI)", tlog_train_rsi),
                    ("Test Log (Base)", tlog_base), ("Test Log (RSI)", tlog_rsi)]

    for sheet_name, tlog in log_sheets:
        if tlog is None: continue
        wst = wb.create_sheet(sheet_name)
        wst.append(tlog_headers)
        style_header_row(wst, s)
        for row_data in tlog:
            wst.append(row_data)
            try:
                fill = s["green_fill"] if float(str(wst.cell(wst.max_row,8).value).replace("%","")) >= 0 else s["red_fill"]
            except: fill = s["green_fill"]
            for cell in wst[wst.max_row]:
                cell.fill = fill; cell.border = s["thin_border"]; cell.alignment = s["center_align"]
        auto_col_width(wst); wst.freeze_panes = "A2"

    ws4 = wb.create_sheet("Grid Search Train Z+SLTP")
    ws4.append(["Rank","z_entry","z_exit","Window","SL","TP","RR Ratio","Total Return (%)","Sharpe Ratio","Max Drawdown (%)","Win Rate (%)","Trades","SL Hits","TP Hits","Z-Exits"])
    style_header_row(ws4, s)
    for rank, rd in gs_base_df.reset_index().iterrows():
        sl_v = rd["SL"]; tp_v = rd["TP"]
        rr_str = (f"1 : {tp_v/sl_v:.1f}" if sl_v < 999 and tp_v < 999
                  else "No SL / No TP" if sl_v >= 999 and tp_v >= 999
                  else f"No SL / TP {fmt_sl_tp(tp_v)}" if sl_v >= 999
                  else f"SL {fmt_sl_tp(sl_v)} / No TP")
        row = [rank+1, rd["z_entry"], rd["z_exit"], int(rd["window"]),
               fmt_sl_tp(sl_v), fmt_sl_tp(tp_v), rr_str,
               rd["Total Return (%)"], rd["Sharpe Ratio"], rd["Max Drawdown (%)"],
               rd["Win Rate (%)"], rd["Trades"], rd["SL Hits"], rd["TP Hits"], rd["Z-Exits"]]
        ws4.append(row)
        fill = s["gold_fill"] if rank == 0 else s["hold_fill"]
        for cell in ws4[ws4.max_row]:
            cell.fill = fill; cell.font = Font(name="Arial", bold=(rank==0), size=11)
            cell.border = s["thin_border"]; cell.alignment = s["center_align"]
    auto_col_width(ws4); ws4.freeze_panes = "A2"

    ws5 = wb.create_sheet("Grid Search Train RSI")
    ws5.append(["Rank","RSI Period","RSI Threshold","Total Return (%)","Sharpe Ratio","Max Drawdown (%)","Win Rate (%)","Trades","SL Hits","TP Hits","Z-Exits"])
    style_header_row(ws5, s)
    for rank, rd in gs_rsi_df.reset_index().iterrows():
        row = [rank+1, int(rd["rsi_period"]), int(rd["rsi_threshold"]),
               rd["Total Return (%)"], rd["Sharpe Ratio"], rd["Max Drawdown (%)"],
               rd["Win Rate (%)"], rd["Trades"], rd["SL Hits"], rd["TP Hits"], rd["Z-Exits"]]
        ws5.append(row)
        fill = s["gold_fill"] if rank == 0 else s["hold_fill"]
        for cell in ws5[ws5.max_row]:
            cell.fill = fill; cell.font = Font(name="Arial", bold=(rank==0), size=11)
            cell.border = s["thin_border"]; cell.alignment = s["center_align"]
    auto_col_width(ws5); ws5.freeze_panes = "A2"

    ws6 = wb.create_sheet("Equity Curve")
    ws6.append(["Date","Base Strategy","RSI Strategy","Buy & Hold Y","Buy & Hold X"])
    style_header_row(ws6, s)
    for idx, row in df[["Equity_Base","Equity_RSI","BH_Y","BH_X"]].dropna().iterrows():
        ws6.append([idx.date(), round(float(row["Equity_Base"]),6), round(float(row["Equity_RSI"]),6),
                    round(float(row["BH_Y"]),6), round(float(row["BH_X"]),6)])
    for col in ws6.columns:
        ws6.column_dimensions[get_column_letter(col[0].column)].width = 18
    ws6.freeze_panes = "A2"

    sfm = {"Buy Y": s["buy_y_fill"], "Buy X": s["buy_x_fill"], "Exit": s["exit_fill"], "Hold": s["hold_fill"]}
    for sheet_name, res, include_rsi in [("Price & Signal (Base)", res_base, False), ("Price & Signal (RSI)", res_rsi, True)]:
        wsx    = wb.create_sheet(sheet_name)
        pos_s  = res["position"]
        prev_p = pos_s.shift(1).fillna(0)
        sig_s  = pd.Series("Hold", index=df.index)
        sig_s[(prev_p == 0) & (pos_s ==  1)] = "Buy Y"
        sig_s[(prev_p == 0) & (pos_s == -1)] = "Buy X"
        sig_s[(prev_p != 0) & (pos_s ==  0)] = "Exit"
        cum_pnl = (res["equity"] - 1) * 100
        strat_r = res["strat_ret"] * 100

        header_base = ["Date", f"Price Y ({A})", f"Price X ({B})", f"Z-Score (win={window})"]
        if include_rsi:
            header_base += [f"RSI Y (p={rsi_period_best})", f"RSI X (p={rsi_period_best})"]
        header_base += ["Signal", "Position", "Exit Reason", "Daily PnL (%)", "Cum PnL (%)"]
        wsx.append(header_base)
        style_header_row(wsx, s)

        for idx in df.index:
            row    = df.loc[idx]
            z_val  = row["Z"]
            sig    = sig_s.loc[idx]
            pos_lb = "Long Y" if int(pos_s.loc[idx]) == 1 else ("Long X" if int(pos_s.loc[idx]) == -1 else "-")
            ex_r   = res["exit_rsn"].loc[idx] if res["exit_rsn"].loc[idx] != "" else "-"

            data_row = [idx.date(), round(float(row["Y"]),4), round(float(row["X"]),4),
                        round(float(z_val),4) if pd.notna(z_val) else "-"]
            if include_rsi and rsi_y_series is not None and rsi_x_series is not None:
                ry = rsi_y_series.loc[idx] if idx in rsi_y_series.index else np.nan
                rx = rsi_x_series.loc[idx] if idx in rsi_x_series.index else np.nan
                ry_val = round(float(ry), 2) if pd.notna(ry) else "-"
                rx_val = round(float(rx), 2) if pd.notna(rx) else "-"
                data_row += [ry_val, rx_val]
            data_row += [sig, pos_lb, ex_r, round(float(strat_r.loc[idx]),4), round(float(cum_pnl.loc[idx]),4)]
            wsx.append(data_row)

            fill = sfm.get(sig, s["hold_fill"])
            for cell in wsx[wsx.max_row]:
                cell.fill = fill; cell.border = s["thin_border"]; cell.alignment = s["center_align"]

            if include_rsi and rsi_y_series is not None:
                for col_idx, rv in [(5, ry_val), (6, rx_val)]:
                    rc = wsx.cell(wsx.max_row, col_idx)
                    if isinstance(rv, float):
                        rc.fill = PatternFill("solid", start_color="FFD966") if rv <= rsi_thresh_best else s["hold_fill"]

        for i, w in enumerate([14,14,14,22,14,14,10,10,14,16,18] if include_rsi else [14,14,14,22,10,10,14,16,18], 1):
            wsx.column_dimensions[get_column_letter(i)].width = w
        wsx.freeze_panes = "A2"

# ── MAIN LOOP ──────────────────────────────────────────────────────────────────
failed_pairs  = []
direction_log = []

valid_z_combos    = [(ze, zx) for ze, zx in iproduct(entry_thresholds, exit_thresholds) if zx < ze]
total_base_combos = len(valid_z_combos) * len(window_list) * len(sl_tp_pairs)
total_rsi_combos  = len(rsi_periods) * len(rsi_thresholds)

print(f"Total pairs        : {len(all_pairs)}")
print(f"  Cointegration    : {len(COINTEGRATION_PAIRS)}")
print(f"  Pearson/Spearman : {len(PEARSON_SPEARMAN_PAIRS)}")
print(f"Train period       : {train_start} → {train_end}")
print(f"Test period (OOS)  : {test_start} → {test_end}")
print(f"Total base combos  : {total_base_combos}")
print(f"Total RSI combos   : {total_rsi_combos}")
print(f"Min trades (train) : {MIN_TRAIN_TRADES}")

for pair_idx, pair in enumerate(all_pairs):
    raw_A, raw_B     = pair.split("-")
    is_cointegration = pair in COINTEGRATION_SET

    print(f"\n{'='*65}")
    print(f"[{pair_idx+1}/{len(all_pairs)}] Processing: {raw_A} - {raw_B} "
          f"({'Cointegration' if is_cointegration else 'Pearson/Spearman'})")
    print(f"{'='*65}")

    try:
        # ── AMBIL DATA DARI all_df (per-ticker individual) ─────────────────────
        close_a = close_b = None
        for sektor_df in all_df.values():
            if raw_A in sektor_df.columns and close_a is None:
                close_a = sektor_df[raw_A].dropna()
            if raw_B in sektor_df.columns and close_b is None:
                close_b = sektor_df[raw_B].dropna()

        if close_a is None or close_b is None:
            missing = [t for t, s in [(raw_A, close_a), (raw_B, close_b)] if s is None]
            print(f"  Skip: ticker {missing} tidak ditemukan")
            failed_pairs.append((pair, f"ticker tidak ditemukan: {missing}"))
            continue

        # Filter rentang tanggal sejak buffer
        close_a = close_a.loc[data_start:data_end]
        close_b = close_b.loc[data_start:data_end]

        # Fix manual TMAS
        if raw_B == 'TMAS' or raw_A == 'TMAS':
            tmas_series = close_b if raw_B == 'TMAS' else close_a
            tmas_fix_date = pd.Timestamp("2023-05-23")
            if tmas_fix_date in tmas_series.index:
                tmas_series.loc[tmas_fix_date] = 294

        # Align hanya untuk pair ini
        common_idx = close_a.index.intersection(close_b.index)
        close_a    = close_a.loc[common_idx]
        close_b    = close_b.loc[common_idx]

        # ── TENTUKAN ARAH Y / X ────────────────────────────────────────────────
        direction_info = None

        if is_cointegration:
            A, B = raw_A, raw_B
            print(f"  [Cointegration] Arah tetap: Y={A}, X={B}")
        else:
            print(f"  [Pearson/Spearman] Menentukan arah terbaik via ADF p-value...")

            # Gunakan hanya data train untuk tentukan arah (konsisten dengan periode analisis)
            common_train = common_idx[(common_idx >= train_start) & (common_idx <= train_end)]
            close_a_train = close_a.loc[common_train]
            close_b_train = close_b.loc[common_train]

            (price_y, price_x, ticker_y, ticker_x,
             pval_chosen, pval_alt, direction_chosen) = determine_direction_by_adf(
                close_a_train, close_b_train, raw_A, raw_B
            )
            A, B = ticker_y, ticker_x

            direction_info = {
                "direction":   f"{A}~{B} (ADF p={pval_chosen:.4f}) vs {raw_B if A==raw_A else raw_A}~{A if A==raw_B else raw_B} (ADF p={pval_alt:.4f})",
                "pval_chosen": pval_chosen,
                "pval_alt":    pval_alt,
                "dir_code":    direction_chosen,
            }

            direction_log.append({
                "Pair (Original)":  pair,
                "Y (Dependen)":     A,
                "X (Independen)":   B,
                "ADF p-val Y~X":    round(pval_chosen, 6),
                "ADF p-val X~Y":    round(pval_alt, 6),
                "Direction Chosen": direction_chosen,
            })

            print(f"  ADF p-value  {raw_A}~{raw_B} = {pval_chosen:.6f}  |  {raw_B}~{raw_A} = {pval_alt:.6f}")
            print(f"  → Pilih: Y={A}, X={B}  (p-value terkecil = {min(pval_chosen, pval_alt):.6f})")

        # ── BUAT df_full ───────────────────────────────────────────────────────
        col_y = close_a if A == raw_A else close_b
        col_x = close_b if B == raw_B else close_a

        df_full = pd.concat([col_y.rename("Y"), col_x.rename("X")], axis=1).dropna()

        # ── ROLLING OLS (hedge ratio dinamis) ─────────────────────────────────
        X_full     = sm.add_constant(df_full["X"])
        roll_model = RollingOLS(df_full["Y"], X_full, window=OLS_WINDOW).fit()
        alpha_t    = roll_model.params["const"]
        beta_t     = roll_model.params["X"]
        df_full["Dynamic_Spread"] = df_full["Y"] - (alpha_t + beta_t * df_full["X"])

        # ── TRAIN / TEST SPLIT (sesuai date ranges) ────────────────────────────
        df_train = df_full.loc[train_start:train_end].copy()
        df_test  = df_full.loc[test_start:test_end].copy()

        if len(df_train) < 100 or len(df_test) < 50:
            print(f"  Skip: train={len(df_train)} rows, test={len(df_test)} rows")
            failed_pairs.append((pair, "train/test too short"))
            continue

        for dff in [df_train, df_test]:
            dff["Ret_Y"] = dff["Y"].pct_change().fillna(0)
            dff["Ret_X"] = dff["X"].pct_change().fillna(0)
            dff["BH_Y"]  = (1 + dff["Ret_Y"]).cumprod()
            dff["BH_X"]  = (1 + dff["Ret_X"]).cumprod()

        print(f"  Y={A} | X={B}")
        print(f"  Train : {df_train.index[0].date()} → {df_train.index[-1].date()} ({len(df_train)} rows)")
        print(f"  Test  : {df_test.index[0].date()} → {df_test.index[-1].date()} ({len(df_test)} rows)")

        # ── PHASE 1: Grid Search Z + SL/TP on TRAIN ───────────────────────────
        print(f"\n  [PHASE 1 - TRAIN] Grid search Z + SL/TP ({total_base_combos} combos)...")
        gs_base = []
        counter = 0

        for z_entry, z_ex, win, (sl, tp) in iproduct(entry_thresholds, exit_thresholds, window_list, sl_tp_pairs):
            if z_ex >= z_entry: continue
            counter += 1
            _, z_s_train = calc_zscore(df_train, win)
            r = run_backtest(df_train, z_s_train, z_entry, -z_entry, z_ex, sl, tp)
            gs_base.append({
                "z_entry": z_entry, "z_exit": z_ex, "window": win, "SL": sl, "TP": tp,
                "Total Return (%)": round(r["total_ret"]*100, 2),
                "Sharpe Ratio":     round(r["sharpe"], 4),
                "Max Drawdown (%)": round(r["mdd"]*100, 2),
                "Win Rate (%)":     round(r["win_rate"]*100, 2),
                "Trades": r["n_trades"], "SL Hits": r["n_sl"], "TP Hits": r["n_tp"], "Z-Exits": r["n_ze"],
            })
            if counter % 100 == 0 or counter == total_base_combos:
                print(f"    [{counter}/{total_base_combos}] ...", end="\r")

        gs_base_df  = pd.DataFrame(gs_base)
        valid_gs_df = gs_base_df[gs_base_df["Trades"] >= MIN_TRAIN_TRADES]
        if valid_gs_df.empty: valid_gs_df = gs_base_df[gs_base_df["Trades"] >= 5]
        if valid_gs_df.empty: valid_gs_df = gs_base_df

        gs_base_df   = valid_gs_df.sort_values("Sharpe Ratio", ascending=False).reset_index(drop=True)
        gs_base_df.index += 1

        best    = gs_base_df.iloc[0]
        z_atas  = best["z_entry"]; z_bawah = -best["z_entry"]; z_exit = best["z_exit"]
        window  = int(best["window"]); sl_best = best["SL"]; tp_best = best["TP"]
        print(f"\n  Best Z+SL/TP: z=±{z_atas} exit={z_exit} win={window} "
              f"SL={fmt_sl_tp(sl_best)} TP={fmt_sl_tp(tp_best)} Sharpe={best['Sharpe Ratio']:.4f} | Trades={int(best['Trades'])}")

        # ── PHASE 2: Grid Search RSI on TRAIN ─────────────────────────────────
        print(f"\n  [PHASE 2 - TRAIN] Grid search RSI ({total_rsi_combos} combos)...")
        gs_rsi  = []
        counter = 0
        _, z_best_train = calc_zscore(df_train, window)

        for rp, rt in iproduct(rsi_periods, rsi_thresholds):
            counter += 1
            rsi_y_train = calc_rsi(df_train["Y"], rp)
            rsi_x_train = calc_rsi(df_train["X"], rp)
            r = run_backtest(df_train, z_best_train, z_atas, z_bawah, z_exit, sl_best, tp_best,
                             rsi_y=rsi_y_train, rsi_x=rsi_x_train, rsi_threshold=rt)
            gs_rsi.append({
                "rsi_period": rp, "rsi_threshold": rt,
                "Total Return (%)": round(r["total_ret"]*100, 2),
                "Sharpe Ratio":     round(r["sharpe"], 4),
                "Max Drawdown (%)": round(r["mdd"]*100, 2),
                "Win Rate (%)":     round(r["win_rate"]*100, 2),
                "Trades": r["n_trades"], "SL Hits": r["n_sl"], "TP Hits": r["n_tp"], "Z-Exits": r["n_ze"],
            })
            if counter % 20 == 0: print(f"    [{counter}/{total_rsi_combos}] ...", end="\r")

        gs_rsi_df       = pd.DataFrame(gs_rsi).sort_values("Sharpe Ratio", ascending=False).reset_index(drop=True)
        gs_rsi_df.index += 1
        best_rsi        = gs_rsi_df.iloc[0]
        rsi_period_best = int(best_rsi["rsi_period"]); rsi_thresh_best = int(best_rsi["rsi_threshold"])
        print(f"\n  Best RSI: period={rsi_period_best}, threshold={rsi_thresh_best}, "
              f"Sharpe={best_rsi['Sharpe Ratio']:.4f} | Trades={int(best_rsi['Trades'])}")

        # ── PHASE 3: OUT-OF-SAMPLE TEST ───────────────────────────────────────
        print(f"\n  [PHASE 3 - TEST OOS] Applying frozen params to {test_start} → {test_end}...")
        _, z_best_test = calc_zscore(df_test, window)
        df_test["Z"]   = z_best_test

        res_test_base  = run_backtest(df_test, z_best_test, z_atas, z_bawah, z_exit, sl_best, tp_best)
        df_test["Equity_Base"] = res_test_base["equity"]
        tlog_test_base = build_trade_log(df_test, res_test_base)

        rsi_y_test_final = calc_rsi(df_test["Y"], rsi_period_best)
        rsi_x_test_final = calc_rsi(df_test["X"], rsi_period_best)
        res_test_rsi     = run_backtest(df_test, z_best_test, z_atas, z_bawah, z_exit, sl_best, tp_best,
                                        rsi_y=rsi_y_test_final, rsi_x=rsi_x_test_final, rsi_threshold=rsi_thresh_best)
        df_test["Equity_RSI"] = res_test_rsi["equity"]
        tlog_test_rsi    = build_trade_log(df_test, res_test_rsi)
        print(f"  Test Base: {len(tlog_test_base)} trades | Test RSI: {len(tlog_test_rsi)} trades")

        # ── TRAIN LOGS ─────────────────────────────────────────────────────────
        res_train_base  = run_backtest(df_train, z_best_train, z_atas, z_bawah, z_exit, sl_best, tp_best)
        tlog_train_base = build_trade_log(df_train, res_train_base)

        rsi_y_train_best = calc_rsi(df_train["Y"], rsi_period_best)
        rsi_x_train_best = calc_rsi(df_train["X"], rsi_period_best)
        res_train_rsi    = run_backtest(df_train, z_best_train, z_atas, z_bawah, z_exit, sl_best, tp_best,
                                        rsi_y=rsi_y_train_best, rsi_x=rsi_x_train_best, rsi_threshold=rsi_thresh_best)
        tlog_train_rsi   = build_trade_log(df_train, res_train_rsi)

        # ── SAVE EXCEL ─────────────────────────────────────────────────────────
        wb_out          = Workbook()
        pair_type_label = "cointegration" if is_cointegration else "pearson_spearman"
        write_excel(wb_out, A, B, df_test, res_test_base, res_test_rsi,
                    tlog_test_base, tlog_test_rsi, gs_base_df, gs_rsi_df,
                    window, z_atas, z_exit, sl_best, tp_best,
                    rsi_period_best, rsi_thresh_best,
                    rsi_y_series=rsi_y_test_final, rsi_x_series=rsi_x_test_final,
                    tlog_train_base=tlog_train_base, tlog_train_rsi=tlog_train_rsi,
                    pair_type=pair_type_label, direction_info=direction_info)

        output_path = f"BT_RSI/{A}-{B}.xlsx"
        wb_out.save(output_path)
        print(f"  Saved: {output_path}")

    except Exception as e:
        import traceback
        print(f"  Error on {pair}: {e}")
        traceback.print_exc()
        failed_pairs.append((pair, str(e)))

# ── FINAL SUMMARY ──────────────────────────────────────────────────────────────
print(f"\n{'='*65}")
print(f"Completed: {len(all_pairs) - len(failed_pairs)}/{len(all_pairs)} pairs successful")
if failed_pairs:
    print("Failed pairs:")
    for p, reason in failed_pairs:
        print(f"   - {p}: {reason}")

if direction_log:
    print(f"\n{'='*65}")
    print("DIRECTION SELECTION LOG (Pearson/Spearman Pairs)")
    print(f"{'='*65}")
    df_dir_log = pd.DataFrame(direction_log)
    print(df_dir_log.to_string(index=False))
    df_dir_log.to_csv("BT_RSI/direction_selection_log.csv", index=False)
    print(f"\nDirection log saved to: BT_RSI/direction_selection_log.csv")

Total pairs        : 23
  Cointegration    : 11
  Pearson/Spearman : 12
Train period       : 2022-01-01 → 2023-12-31
Test period (OOS)  : 2024-01-01 → 2025-12-31
Total base combos  : 297
Total RSI combos   : 12
Min trades (train) : 10

=================================================================
[1/23] Processing: SOSS - SKRN (Cointegration)
=================================================================
  [Cointegration] Arah tetap: Y=SOSS, X=SKRN
  Y=SOSS | X=SKRN
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±1.5 exit=0.5 win=20 SL=3% TP=6% Sharpe=1.8016 | Trades=49

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=10, threshold=40, Sharpe=1.3899 | Trades=26

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 39 trades | Test RSI: 21 trades
  Saved: BT_RSI/SOSS-SKRN.xlsx

=================================================================
[2/23] Processing: KOPI - DWGL (Cointegration)
=================================================================
  [Cointegration] Arah tetap: Y=KOPI, X=DWGL
  Y=KOPI | X=DWGL
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±1.5 exit=0.25 win=20 SL=7% TP=Disabled Sharpe=0.9127 | Trades=25

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=7, threshold=25, Sharpe=1.3064 | Trades=13

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 26 trades | Test RSI: 13 trades
  Saved: BT_RSI/KOPI-DWGL.xlsx

=================================================================
[3/23] Processing: PICO - ALMI (Cointegration)
=================================================================
  [Cointegration] Arah tetap: Y=PICO, X=ALMI
  Y=PICO | X=ALMI
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±2.0 exit=0.25 win=20 SL=4% TP=8% Sharpe=1.2115 | Trades=29

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=7, threshold=40, Sharpe=1.4602 | Trades=18

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 16 trades | Test RSI: 10 trades
  Saved: BT_RSI/PICO-ALMI.xlsx

=================================================================
[4/23] Processing: JAST - OASA (Cointegration)
=================================================================
  [Cointegration] Arah tetap: Y=JAST, X=OASA
  Y=JAST | X=OASA
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±1.5 exit=0.0 win=40 SL=5% TP=10% Sharpe=1.1071 | Trades=24

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=10, threshold=40, Sharpe=1.4957 | Trades=13

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 20 trades | Test RSI: 14 trades
  Saved: BT_RSI/JAST-OASA.xlsx

=================================================================
[5/23] Processing: AKSI - HELI (Cointegration)
=================================================================
  [Cointegration] Arah tetap: Y=AKSI, X=HELI
  Y=AKSI | X=HELI
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±2.0 exit=0.5 win=20 SL=5% TP=8% Sharpe=1.2593 | Trades=23

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=14, threshold=40, Sharpe=1.3053 | Trades=15

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 24 trades | Test RSI: 11 trades
  Saved: BT_RSI/AKSI-HELI.xlsx

=================================================================
[6/23] Processing: JMAS - BBRI (Cointegration)
=================================================================
  [Cointegration] Arah tetap: Y=JMAS, X=BBRI
  Y=JMAS | X=BBRI
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±2.0 exit=0.0 win=20 SL=3% TP=6% Sharpe=0.8795 | Trades=16

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=7, threshold=40, Sharpe=0.5532 | Trades=18

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 18 trades | Test RSI: 14 trades
  Saved: BT_RSI/JMAS-BBRI.xlsx

=================================================================
[7/23] Processing: NZIA - PAMG (Cointegration)
=================================================================
  [Cointegration] Arah tetap: Y=NZIA, X=PAMG
  Y=NZIA | X=PAMG
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±2.0 exit=0.5 win=40 SL=5% TP=10% Sharpe=1.1158 | Trades=14

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=14, threshold=25, Sharpe=0.9559 | Trades=6

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 17 trades | Test RSI: 3 trades
  Saved: BT_RSI/NZIA-PAMG.xlsx

=================================================================
[8/23] Processing: ATIC - DIVA (Cointegration)
=================================================================
  [Cointegration] Arah tetap: Y=ATIC, X=DIVA
  Y=ATIC | X=DIVA
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±2.5 exit=0.25 win=20 SL=3% TP=4% Sharpe=1.3110 | Trades=13

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=14, threshold=40, Sharpe=1.3110 | Trades=13

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 10 trades | Test RSI: 4 trades
  Saved: BT_RSI/ATIC-DIVA.xlsx

=================================================================
[9/23] Processing: SKBM - MGRO (Cointegration)
=================================================================
  [Cointegration] Arah tetap: Y=SKBM, X=MGRO
  Y=SKBM | X=MGRO
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±1.5 exit=0.5 win=20 SL=2% TP=4% Sharpe=1.7660 | Trades=41

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=7, threshold=40, Sharpe=1.6597 | Trades=28

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 44 trades | Test RSI: 31 trades
  Saved: BT_RSI/SKBM-MGRO.xlsx

=================================================================
[10/23] Processing: GDYR - GLOB (Cointegration)
=================================================================
  [Cointegration] Arah tetap: Y=GDYR, X=GLOB
  Y=GDYR | X=GLOB
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±1.5 exit=0.5 win=20 SL=2% TP=3% Sharpe=2.2215 | Trades=49

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=7, threshold=40, Sharpe=2.5801 | Trades=27

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 37 trades | Test RSI: 25 trades
  Saved: BT_RSI/GDYR-GLOB.xlsx

=================================================================
[11/23] Processing: MIKA - PRIM (Cointegration)
=================================================================
  [Cointegration] Arah tetap: Y=MIKA, X=PRIM
  Y=MIKA | X=PRIM
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±1.5 exit=0.0 win=60 SL=4% TP=8% Sharpe=0.4868 | Trades=19

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=7, threshold=40, Sharpe=0.3691 | Trades=15

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 21 trades | Test RSI: 17 trades
  Saved: BT_RSI/MIKA-PRIM.xlsx

=================================================================
[12/23] Processing: HEXA - IMPC (Pearson/Spearman)
=================================================================
  [Pearson/Spearman] Menentukan arah terbaik via ADF p-value...
  ADF p-value  HEXA~IMPC = 0.100568  |  IMPC~HEXA = 0.250308
  → Pilih: Y=IMPC, X=HEXA  (p-value terkecil = 0.100568)
  Y=IMPC | X=HEXA
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±2.0 exit=0.0 win=60 SL=5% TP=8% Sharpe=1.3726 | Trades=12

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=10, threshold=25, Sharpe=0.9337 | Trades=1

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 9 trades | Test RSI: 5 trades
  Saved: BT_RSI/IMPC-HEXA.xlsx

=================================================================
[13/23] Processing: ITMG - ADRO (Pearson/Spearman)
=================================================================
  [Pearson/Spearman] Menentukan arah terbaik via ADF p-value...
  ADF p-value  ITMG~ADRO = 0.052248  |  ADRO~ITMG = 0.059360
  → Pilih: Y=ADRO, X=ITMG  (p-value terkecil = 0.052248)
  Y=ADRO | X=ITMG
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±1.5 exit=0.0 win=40 SL=5% TP=8% Sharpe=0.4886 | Trades=19

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=10, threshold=40, Sharpe=0.5721 | Trades=14

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 12 trades | Test RSI: 7 trades
  Saved: BT_RSI/ADRO-ITMG.xlsx

=================================================================
[14/23] Processing: SPMA - UNIC (Pearson/Spearman)
=================================================================
  [Pearson/Spearman] Menentukan arah terbaik via ADF p-value...
  ADF p-value  SPMA~UNIC = 0.009480  |  UNIC~SPMA = 0.139088
  → Pilih: Y=SPMA, X=UNIC  (p-value terkecil = 0.009480)
  Y=SPMA | X=UNIC
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±1.5 exit=0.5 win=20 SL=2% TP=4% Sharpe=1.1521 | Trades=48

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=14, threshold=40, Sharpe=1.2658 | Trades=33

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 39 trades | Test RSI: 23 trades
  Saved: BT_RSI/SPMA-UNIC.xlsx

=================================================================
[15/23] Processing: ADHI - PTPP (Pearson/Spearman)
=================================================================
  [Pearson/Spearman] Menentukan arah terbaik via ADF p-value...
  ADF p-value  ADHI~PTPP = 0.037532  |  PTPP~ADHI = 0.072296
  → Pilih: Y=ADHI, X=PTPP  (p-value terkecil = 0.037532)
  Y=ADHI | X=PTPP
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±2.5 exit=0.25 win=60 SL=2% TP=3% Sharpe=0.8548 | Trades=11

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=7, threshold=40, Sharpe=1.1477 | Trades=5

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 7 trades | Test RSI: 3 trades
  Saved: BT_RSI/ADHI-PTPP.xlsx

=================================================================
[16/23] Processing: SMDR - TMAS (Pearson/Spearman)
=================================================================
  [Pearson/Spearman] Menentukan arah terbaik via ADF p-value...
  ADF p-value  SMDR~TMAS = 0.292985  |  TMAS~SMDR = 0.417846
  → Pilih: Y=SMDR, X=TMAS  (p-value terkecil = 0.292985)
  Y=SMDR | X=TMAS
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±2.0 exit=0.25 win=60 SL=3% TP=Disabled Sharpe=1.5585 | Trades=15

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=14, threshold=25, Sharpe=1.1736 | Trades=7

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 13 trades | Test RSI: 5 trades
  Saved: BT_RSI/SMDR-TMAS.xlsx

=================================================================
[17/23] Processing: PNBN - PNLF (Pearson/Spearman)
=================================================================
  [Pearson/Spearman] Menentukan arah terbaik via ADF p-value...
  ADF p-value  PNBN~PNLF = 0.013035  |  PNLF~PNBN = 0.021468
  → Pilih: Y=PNBN, X=PNLF  (p-value terkecil = 0.013035)
  Y=PNBN | X=PNLF
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±2.0 exit=0.25 win=60 SL=7% TP=Disabled Sharpe=2.2167 | Trades=10

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=10, threshold=40, Sharpe=1.1145 | Trades=5

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 13 trades | Test RSI: 7 trades
  Saved: BT_RSI/PNBN-PNLF.xlsx

=================================================================
[18/23] Processing: BBNI - BMRI (Pearson/Spearman)
=================================================================
  [Pearson/Spearman] Menentukan arah terbaik via ADF p-value...
  ADF p-value  BBNI~BMRI = 0.045140  |  BMRI~BBNI = 0.177167
  → Pilih: Y=BBNI, X=BMRI  (p-value terkecil = 0.045140)
  Y=BBNI | X=BMRI
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±1.5 exit=0.0 win=20 SL=4% TP=8% Sharpe=1.6892 | Trades=13

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=14, threshold=25, Sharpe=1.6757 | Trades=7

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 28 trades | Test RSI: 3 trades
  Saved: BT_RSI/BBNI-BMRI.xlsx

=================================================================
[19/23] Processing: POLL - URBN (Pearson/Spearman)
=================================================================
  [Pearson/Spearman] Menentukan arah terbaik via ADF p-value...
  ADF p-value  POLL~URBN = 0.001173  |  URBN~POLL = 0.038981
  → Pilih: Y=POLL, X=URBN  (p-value terkecil = 0.001173)
  Y=POLL | X=URBN
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±1.5 exit=0.0 win=60 SL=3% TP=6% Sharpe=0.3551 | Trades=20

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=7, threshold=25, Sharpe=0.6890 | Trades=14

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 6 trades | Test RSI: 3 trades
  Saved: BT_RSI/POLL-URBN.xlsx

=================================================================
[20/23] Processing: MLPT - DMMX (Pearson/Spearman)
=================================================================
  [Pearson/Spearman] Menentukan arah terbaik via ADF p-value...
  ADF p-value  MLPT~DMMX = 0.033996  |  DMMX~MLPT = 0.060906
  → Pilih: Y=DMMX, X=MLPT  (p-value terkecil = 0.033996)
  Y=DMMX | X=MLPT
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±2.0 exit=0.5 win=60 SL=7% TP=Disabled Sharpe=0.1740 | Trades=11

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=7, threshold=25, Sharpe=0.4523 | Trades=8

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 18 trades | Test RSI: 9 trades
  Saved: BT_RSI/DMMX-MLPT.xlsx

=================================================================
[21/23] Processing: ADES - AMRT (Pearson/Spearman)
=================================================================
  [Pearson/Spearman] Menentukan arah terbaik via ADF p-value...
  ADF p-value  ADES~AMRT = 0.214260  |  AMRT~ADES = 0.256654
  → Pilih: Y=AMRT, X=ADES  (p-value terkecil = 0.214260)
  Y=AMRT | X=ADES
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±2.0 exit=0.25 win=40 SL=5% TP=10% Sharpe=1.9419 | Trades=14

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=14, threshold=40, Sharpe=2.2140 | Trades=8

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 13 trades | Test RSI: 8 trades
  Saved: BT_RSI/AMRT-ADES.xlsx

=================================================================
[22/23] Processing: MAPI - PANR (Pearson/Spearman)
=================================================================
  [Pearson/Spearman] Menentukan arah terbaik via ADF p-value...
  ADF p-value  MAPI~PANR = 0.002039  |  PANR~MAPI = 0.002705
  → Pilih: Y=MAPI, X=PANR  (p-value terkecil = 0.002039)
  Y=MAPI | X=PANR
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±2.0 exit=0.0 win=60 SL=4% TP=8% Sharpe=2.2249 | Trades=12

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=7, threshold=40, Sharpe=2.2249 | Trades=12

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 14 trades | Test RSI: 11 trades
  Saved: BT_RSI/MAPI-PANR.xlsx

=================================================================
[23/23] Processing: INAF - KAEF (Pearson/Spearman)
=================================================================
  [Pearson/Spearman] Menentukan arah terbaik via ADF p-value...
  ADF p-value  INAF~KAEF = 0.542394  |  KAEF~INAF = 0.703026
  → Pilih: Y=KAEF, X=INAF  (p-value terkecil = 0.542394)
  Y=KAEF | X=INAF
  Train : 2022-01-03 → 2023-12-29 (485 rows)
  Test  : 2024-01-02 → 2025-12-30 (473 rows)

  [PHASE 1 - TRAIN] Grid search Z + SL/TP (297 combos)...
    [297/297] ...
  Best Z+SL/TP: z=±2.0 exit=0.25 win=60 SL=7% TP=Disabled Sharpe=1.2060 | Trades=11

  [PHASE 2 - TRAIN] Grid search RSI (12 combos)...

  Best RSI: period=7, threshold=25, Sharpe=1.2983 | Trades=9

  [PHASE 3 - TEST OOS] Applying frozen params to 2024-01-01 → 2025-12-31...
  Test Base: 5 trades | Test RSI: 4 trades
  Saved: BT_RSI/KAEF-INAF.xlsx

=================================================================
Completed: 23/23 pairs successful

=================================================================
DIRECTION SELECTION LOG (Pearson/Spearman Pairs)
=================================================================
Pair (Original) Y (Dependen) X (Independen)  ADF p-val Y~X  ADF p-val X~Y Direction Chosen
      HEXA-IMPC         IMPC           HEXA       0.100568       0.250308               BA
      ITMG-ADRO         ADRO           ITMG       0.052248       0.059360               BA
      SPMA-UNIC         SPMA           UNIC       0.009480       0.139088               AB